// Spruch-Pool des Moderators. Platzhalter in geschweiften Klammern werden
// zur Laufzeit ersetzt. Der Server führt ein Verbraucht-Set, damit sich
// innerhalb einer Lobby kein Spruch wiederholt.
export const LINES = {
  // {count} = Spielerzahl
  welcome: {
    charmant: [
      'Willkommen bei KICKED OUT. {count} Menschen, ein Pott, jede Menge gute Laune. Los geht es.',
      'Schön, dass ihr da seid. {count} Köpfe, ein gemeinsames Ziel und am Ende trotzdem nur ein Sieger.',
      'Setzt euch bequem hin. {count} Spieler, viele Fragen und ein Moderator, der es gut mit euch meint. Meistens.',
      '{count} Freunde betreten die Bühne. Einer geht als Sieger, der Rest als Geschichte.',
      'Guten Abend. Ihr seid zu {count}. Ich verspreche faire Fragen und unfaire Kommentare.',
      'Herzlich willkommen. {count} Kandidaten, kein Vorwissen nötig, viel Herz erlaubt.',
      'Ihr seid {count}. Genau die richtige Menge für einen schönen Abend mit ein paar Tränen.',
      'Bühne frei für {count} Mutige. Ich bin euer Moderator und heute ausnahmsweise gut gelaunt.',
      'Licht an, Musik an, {count} Spieler bereit. Zeigt mir, was ihr könnt.',
    ],
    bissig: [
      '{count} Spieler. In einer Stunde ist davon einer übrig und die anderen erzählen sich Ausreden.',
      'Willkommen. Ihr seid {count}. Statistisch gesehen sind das {count} Menschen zu viel für einen Pott.',
      'Guten Abend. {count} Selbstbewusstseine betreten den Raum. Mal sehen, wie viele den Abend überleben.',
      'Ihr seid {count}. Ich rechne kurz: Das sind ziemlich viele Rauswürfe bis zum Finale.',
      'Schön, dass ihr Zeit hattet. {count} Leute, die gleich merken, dass Allgemeinbildung Arbeit ist.',
      'Willkommen bei KICKED OUT. {count} Freundschaften betreten die Bühne. Nicht alle verlassen sie wieder.',
      '{count} Kandidaten, ein Pott, keine Gnade. Und ich habe mir Notizen mitgebracht.',
      'Ihr habt euch freiwillig gemeldet, zu {count}. Das merke ich mir für später.',
      'Herzlich willkommen. Bitte lächelt jetzt, gleich habt ihr keinen Grund mehr dazu.',
    ],
    gnadenlos: [
      '{count} Menschen, ein Pott, kein Mitleid. Ich habe Vorhersagen getroffen und sie sind unfreundlich.',
      'Willkommen im Studio. {count} Egos, ein Ausgang. Der Ausgang ist enger, als ihr denkt.',
      'Ihr seid {count}. Am Ende bleibt einer stehen. Die anderen bekommen ein liebevolles Nachwort.',
      'Guten Abend, {count} Hoffnungsvolle. Ich bin die Instanz, die diese Hoffnung heute planmäßig abbaut.',
      '{count} Kandidaten. Das ist keine Gruppe, das ist eine Warteschlange zur Tür.',
      'Willkommen. Ich habe {count} Namen auf meiner Liste und einen sehr guten Radiergummi.',
      'Setzt euch. Von {count} Personen wird heute genau eine glücklich. Rechnet das selbst durch.',
      'Ihr seid {count}. Das Studio hat einen Siegerthron. Das wird ein interessanter Verteilungskampf.',
      'Ihr betretet zu {count} die Bühne. Ich zähle nicht, wie viele rausgehen. Ich werfe sie nur.',
    ],
  },

  // {round} = Rundennummer, {value} = Punktwert pro Frage, {pot} = aktueller Pott
  roundStart: {
    charmant: [
      'Runde {round}. Jede Frage ist {value} Punkte wert. Der Pott steht bei {pot} und will wachsen.',
      'Auf in Runde {round}. {value} Punkte pro Treffer. Ihr schafft das gemeinsam.',
      'Runde {round}, frische Fragen, {value} Punkte das Stück. Atmet einmal tief durch.',
      'Der Pott liegt bei {pot}. In Runde {round} könnt ihr das ordentlich aufstocken.',
      'Neue Runde, neues Glück. Runde {round} steht an, {value} Punkte warten pro Frage.',
      'Runde {round}. Denkt in Ruhe nach. Die Uhr ist ein Vorschlag, allerdings ein sehr strenger.',
      'Wir starten Runde {round}. {value} Punkte, gute Laune, keine Verlierer. Also fast keine.',
      'Pott: {pot}. Runde: {round}. Stimmung: prächtig. Legt los.',
      'Runde {round} beginnt. Jede richtige Antwort bringt {value} Punkte für alle. Teamarbeit, quasi.',
    ],
    bissig: [
      'Runde {round}. {value} Punkte pro Frage. Der Pott steht bei {pot} und schaut euch beim Zögern zu.',
      'Runde {round}. Ab jetzt zählt jede Frage {value} Punkte. Ab jetzt zählt auch jeder Fehler.',
      'Der Pott: {pot}. Eure bisherige Leistung: ausbaufähig. Runde {round} startet.',
      'Runde {round}, {value} Punkte das Stück. Wer jetzt noch raten will, sollte gut raten.',
      'Runde {round}. Die Fragen werden teurer, ihr leider nicht besser.',
      'Wir sind bei Runde {round} und {pot} im Pott. Beides könnte höher sein.',
      'Runde {round}. {value} Punkte pro Antwort. Das ist mehr, als manche hier heute eingezahlt haben.',
      'Neue Runde, Nummer {round}. Gleiche Spieler, gleiche Wissenslücken, höherer Einsatz.',
      'Runde {round} läuft. Der Pott steht bei {pot}. Bitte tut so, als wäre euch das wichtig.',
    ],
    gnadenlos: [
      'Runde {round}. {value} Punkte pro Frage. Der Pott bei {pot} ist der einzige Grund, warum ihr noch sitzt.',
      'Runde {round}. Ab hier trennt sich Wissen von Selbstüberschätzung. Ihr wisst, wo ihr steht.',
      '{value} Punkte pro Frage in Runde {round}. Verdient sie euch oder verschwindet leise.',
      'Pott {pot}, Runde {round}. Die Zahlen steigen, euer Niveau bleibt tapfer konstant.',
      'Runde {round} beginnt. Ich habe die Fragen gesehen. Ihr werdet sie nicht mögen.',
      'Runde {round}. {value} Punkte. Und für jede falsche Antwort ein Eintrag in meinem Gedächtnis.',
      'Der Pott steht bei {pot}. Erschreckend wenig für so viel Selbstvertrauen in diesem Raum.',
      'Runde {round}. Wer jetzt noch von Glück lebt, hat gleich einen Termin mit der Tür.',
      'Runde {round}. {value} Punkte pro Treffer, null Punkte für Ausreden. Los.',
    ],
  },

  // {chain} = neuer Multiplikator, {pot} = aktueller Pott
  chainForged: {
    charmant: [
      'Alle richtig. Die Kette wächst auf {chain}. Der Pott steht bei {pot} und strahlt.',
      'Perfekt gemacht. Ein neues Kettenglied glüht, Multiplikator {chain}.',
      'Sauber, wirklich sauber. Die Kette steht auf {chain}, im Pott liegen {pot}.',
      'Keiner daneben. Das ist Teamarbeit. Die Kette zeigt jetzt {chain}.',
      'Ihr habt es gemeinsam geschafft. Kette {chain}, Pott {pot}. Weiter so.',
      'Ein Glied mehr. {chain} funkelt, und ihr habt es euch verdient.',
      'Alle richtig, kein Zittern. Kette auf {chain}. Das war schön anzusehen.',
      'Die Kette wächst auf {chain}. Merkt euch dieses Gefühl, es hält selten lange.',
      'Volltreffer auf ganzer Linie. Pott {pot}, Kette {chain}. Genießt den Moment.',
    ],
    bissig: [
      'Alle richtig. Überraschend. Kette auf {chain}, Pott auf {pot}.',
      'Ein Kettenglied mehr, {chain}. Ich vermerke das als Zufall in meinem Protokoll.',
      'Nicht schlecht. Die Kette steht auf {chain}. Jetzt bitte nicht sofort alles kaputtmachen.',
      'Kette {chain}. Ihr könnt es also. Interessant, dass ihr das bisher geheim gehalten habt.',
      'Alle richtig. Der Pott bei {pot} atmet hörbar erleichtert auf.',
      'Die Kette wächst auf {chain}. Ein Hoch auf neunzig Sekunden kollektive Konzentration.',
      'Multiplikator {chain}. Ihr fühlt euch jetzt großartig. Der gefährlichste Moment des Spiels.',
      'Kein einziger Fehler. Ich muss meine Vorurteile kurz aktualisieren. Kette {chain}.',
      'Pott {pot}, Kette {chain}. Und irgendwo im Raum plant schon jemand den Bruch.',
    ],
    gnadenlos: [
      'Alle richtig. Kette {chain}. Genießt es, denn die Statistik ist eine kalte Person.',
      'Die Kette steht auf {chain}. Sie hängt an Nerven, und Nerven reißen schneller als Metall.',
      'Kette {chain}, Pott {pot}. Der Pott wird schwer. Schwer genug, um jemanden zu erdrücken.',
      'Ein neues Glied. Ihr baut euch gerade sehr fleißig eure eigene Fallhöhe.',
      'Kette {chain}. Je höher sie steigt, desto lauter knallt es beim Bruch. Ich freue mich.',
      'Alle richtig. Beeindruckend. Beeindruckend war auch die Titanic, kurz vor Mitternacht.',
      'Multiplikator {chain}, Pott {pot}. Einer von euch schreibt gleich Geschichte. Die falsche Sorte.',
      'Die Kette glüht auf {chain}. Erhitztes Metall ist übrigens besonders spröde.',
      'Kette {chain}. Ihr habt gerade gemeinsam etwas Schönes gebaut. Damit es jemand zerstören kann.',
    ],
  },

  // {name} = Kettenbrecher, {chain} = verlorener Multiplikator, {wrong} = falsche Antwort
  chainBreak: {
    charmant: [
      '{name}, du hast die Kette bei {chain} erwischt. Passiert den Besten. Kopf hoch.',
      'Kalt geworden. {name} tippte auf {wrong} und die Kette schläft wieder bei eins.',
      '{name}, das war knapp daneben. {wrong} klang wirklich plausibel.',
      'Die Kette bricht bei {chain}. {name}, das nehmen wir dir nicht übel. Fast nicht.',
      '{name} hat {wrong} gewählt. Mutig. Falsch, aber mutig.',
      'Und Frost. {name}, die Kette bei {chain} war eine schöne Zeit. Danke dafür.',
      '{name}, du warst so nah dran. {wrong} war ein ehrenwerter Irrtum.',
      'Kette gebrochen bei {chain}. {name}, im Herzen machst du das trotzdem richtig.',
      'Ein Splittern. {name} sagte {wrong}, das Universum sagte nein.',
      '{name}, jeder bricht mal eine Kette. Heute warst eben du dran.',
      'Von {chain} zurück auf Anfang. {name}, wir bauen sie einfach neu.',
      '{wrong} war es leider nicht. {name}, du bekommst trotzdem Applaus von mir.',
      '{name}, deine Antwort hatte Charme. Nur eben keine Richtigkeit.',
      'Die Kette ist eingefroren. {name}, hol dir eine Decke und die nächste Frage.',
      '{name} hat sich für {wrong} entschieden. Eine Entscheidung mit Persönlichkeit.',
      'Bei {chain} war Schluss. {name}, kein Drama, das Spiel läuft weiter.',
    ],
    bissig: [
      '{name}. {wrong}. Und schon ist die Kette bei {chain} Geschichte.',
      'Frost. {name} hat {chain} Glieder mit einem einzigen Klick zerlegt. Effizient.',
      '{name}, {wrong} war deine Antwort. Der Rest des Raums hätte gern ein Wort mit dir.',
      'Die Kette lag bei {chain}. Dann kam {name}.',
      '{name} tippt {wrong} und die Temperatur im Studio fällt spürbar.',
      'Splitter überall. Danke, {name}, das war Teamarbeit auf eine sehr eigene Art.',
      '{chain} Glieder, hart erarbeitet, in 0,4 Sekunden entsorgt. {name}, Respekt.',
      '{name}, war {wrong} eine Antwort oder ein Hilferuf?',
      'Kette weg. {name}, du hast heute schon nützlichere Beiträge geleistet. Glaube ich.',
      'Und dann sagte {name} einfach {wrong}. Ende der Sendung für die Kette.',
      '{name} hat gerade {chain} mal Teamarbeit in einen Eiswürfel verwandelt.',
      'Ich hoffe, {wrong} war es dir wert, {name}. Die anderen hoffen etwas anderes.',
      '{name}, du hast die Kette gebrochen. Nicht wegsehen, die Blicke gelten dir.',
      'Von {chain} auf null. {name}, das nennt man einen sauberen Rückbau.',
      '{name} war sich sehr sicher bei {wrong}. Sicherheit ist eben kein Wissensersatz.',
      'Eiszeit. Ausgelöst von {name}, gesponsert von {wrong}.',
    ],
    gnadenlos: [
      '{name} sagt {wrong} und {chain} Glieder zerspringen. Das ist keine Antwort, das ist Sachbeschädigung.',
      'Die Kette stand bei {chain}. {name} hat sie mit bloßen Händen erledigt.',
      '{name}, {wrong}. Irgendwo weint gerade ein Lehrbuch.',
      'Applaus für {name}: {chain} Glieder Teamarbeit, ein Klick, alles weg.',
      '{wrong}, sagt {name}, und der ganze Raum lernt ein neues Wort für Enttäuschung.',
      '{name} hat die Kette nicht gebrochen. {name} hat sie hingerichtet.',
      'Von {chain} auf eins. {name}, du bist heute das Naturereignis, vor dem gewarnt wird.',
      '{name}, wenn Unwissen Punkte gäbe, wärst du längst im Finale.',
      'Frost, Splitter, {name}. In dieser Reihenfolge und mit dieser Verantwortlichkeit.',
      '{chain} Glieder. Weg. Wegen {wrong}. {name}, das kommt in den Abspann.',
      '{name} klickt {wrong} und die anderen rechnen bereits ihre Rachegelüste durch.',
      'Die Kette war stärker als Stahl. Sie war nur nicht stärker als {name}.',
      '{name}, du hast bei {chain} gezündet. Der Krater ist beachtlich.',
      'Es gibt viele Wege, Punkte zu vernichten. {name} wählte den schnellsten: {wrong}.',
      '{name}, deine Antwort hat {chain} Glieder mit einem Knall in Konfetti verwandelt.',
      'Merkt euch diesen Moment: {chain} Glieder, ein Name, {name}, und die Antwort {wrong}.',
    ],
  },

  // {correct} = die richtige Antwort
  allWrong: {
    charmant: [
      'Niemand hatte sie. Richtig war {correct}. Das war auch wirklich fies gestellt.',
      '{correct}. Alle daneben, aber gemeinsam daneben ist fast schon romantisch.',
      'Keiner hat getroffen. Gesucht war {correct}. Merkt es euch für den nächsten Kneipenabend.',
      'Kollektiver Fehlgriff. {correct} wäre es gewesen. Kein Grund zur Sorge.',
      'Die Antwort lautete {correct}. Ihr habt euch alle wacker geirrt.',
      'Null Treffer. Immerhin ist niemand allein schuld. {correct} war die Lösung.',
      '{correct}. Diese Frage hat euch alle gleich gemacht. Das hat auch etwas Schönes.',
      'Alle falsch. Aber ehrlich: {correct} muss man erst einmal wissen.',
      'Die Lösung war {correct}. Ihr habt sie zusammen verpasst, also zählt es halb.',
    ],
    bissig: [
      'Alle falsch. {correct}. Ich lasse das kurz so stehen.',
      'Kollektives Versagen. Gesucht war {correct}. Immerhin seid ihr euch einig.',
      '{correct}. Niemand. Nicht einer. Beeindruckende Geschlossenheit.',
      'Die richtige Antwort war {correct}. Der Pott bleibt hungrig.',
      'Ihr habt alle danebengetippt. {correct} wäre es gewesen, falls das jemanden interessiert.',
      'Null aus allen. {correct}. Das nennt man einen Konsens ohne Grundlage.',
      'Interessant. {correct} war so nah und trotzdem völlig unerreichbar.',
      'Kein einziger Treffer. {correct}. Ich hoffe, diese Fragerunde ist versichert.',
      'Alle daneben. Bei {correct} hätte ich sogar aufs Raten gewettet.',
    ],
    gnadenlos: [
      'Alle falsch. {correct}. Ich öffne kurz die Fenster, hier riecht es nach Unwissen.',
      '{correct}. Und keiner war auch nur in der Nähe. Das ist fast künstlerisch.',
      'Null Treffer. Ich habe Steine gesehen, die bei {correct} schneller waren.',
      'Gesucht war {correct}. Gefunden wurde nichts. Von niemandem.',
      'Ihr habt geschlossen versagt. Das schweißt zusammen. {correct} übrigens.',
      'Alle daneben. {correct}. Diese Frage hat heute Abend gewonnen, nicht ihr.',
      '{correct}. Ich sage das laut, damit es wenigstens einmal im Raum ausgesprochen wurde.',
      'Kein Treffer. Der Pott bleibt leer und meine Erwartungen bleiben es auch.',
      'Alle falsch bei {correct}. Ich hoffe, ihr seid in anderen Lebensbereichen kompetenter.',
    ],
  },

  // {pot} = aktueller Pott
  perfectRound: {
    charmant: [
      'Eine ganze Runde ohne Fehler. Der Pott steht bei {pot} und ihr habt euch das verdient.',
      'Makellos. Kein einziger Patzer, {pot} im Pott. Ich bin fast gerührt.',
      'Perfekte Runde. {pot}. Klopft euch gegenseitig auf die Schulter, aber schnell.',
      'Kein Fehler, keine Eiszeit. Der Pott glänzt bei {pot}.',
      'Das war eine Runde wie aus dem Bilderbuch. {pot} als Belohnung.',
      'Sauber durchgespielt. {pot} im Pott und alle noch Freunde.',
      'Fehlerfrei. Ich schreibe mir das auf, so etwas sieht man selten.',
      'Volle Punktzahl für alle. Der Pott bei {pot} bedankt sich.',
      'Eine perfekte Runde. {pot}. Genau so soll das aussehen.',
    ],
    bissig: [
      'Perfekte Runde, {pot} im Pott. Ich hatte Ausreden vorbereitet, jetzt liegen sie nutzlos herum.',
      'Keine Fehler. Der Pott steht bei {pot}. Und trotzdem fliegt gleich einer raus.',
      'Makellos. {pot}. Schade, dass Sympathie nicht in Punkten gemessen wird.',
      'Fehlerfreie Runde. Ihr könnt es also, wenn ihr wollt. Bemerkenswert.',
      'Sauber. {pot} im Pott. Umso schwerer wird gleich die Wahl, wer geht.',
      'Perfekte Runde, {pot}. Jetzt bitte trotzdem jemanden rauswerfen, das ist das Format.',
      'Kein einziger Patzer. Ich brauche fürs Voting neue Argumente. Ihr auch.',
      'Der Pott steht bei {pot}. Und die Ausreden für gleich sind gerade ausverkauft.',
      'Fehlerlos. Genießt es, das ist eure Ausnahme des Abends.',
    ],
    gnadenlos: [
      'Perfekte Runde. {pot}. Und gleich zerstört ihr das alles mit einer anonymen Abstimmung.',
      'Kein Fehler, {pot} im Pott. Das macht es umso brutaler, dass gleich jemand fliegt.',
      'Makellos. Ihr habt bewiesen, dass ihr könnt. Gleich beweist ihr, dass ihr grausam seid.',
      'Fehlerfrei bei {pot}. Wunderschön. Und völlig bedeutungslos für den, der gleich geht.',
      'Eine saubere Runde. Das Voting interessiert das leider überhaupt nicht.',
      'Kein Patzer, {pot} im Pott. Die Freundschaft ist trotzdem gleich vorbei.',
      'Ihr habt geliefert. Jetzt liefert ihr euch gegenseitig ans Messer.',
      'Perfekt. {pot}. Jetzt kommt der Teil, in dem Leistung nichts mehr zählt.',
      'Eine Runde ohne Fehler. Rührend. Gleich sehen wir, wie schnell so etwas vergessen ist.',
    ],
  },

  // {count} = Zahl der wählbaren Kandidaten
  votingOpen: {
    charmant: [
      'Das Voting ist offen. {count} Kandidaten stehen zur Wahl. Seid ehrlich, aber lieb.',
      'Jetzt seid ihr dran. {count} Namen, eine Stimme, eine Begründung.',
      'Die Abstimmung läuft. {count} Menschen hoffen gerade sehr auf eure Nachsicht.',
      'Wählt weise. {count} Kandidaten, und jeder hat sein Bestes gegeben.',
      'Voting offen. Bitte begründet eure Wahl, das gehört zum guten Ton.',
      'Ihr habt {count} Möglichkeiten und ein Gewissen. Viel Erfolg damit.',
      'Handys hoch. {count} Namen warten auf euer Urteil.',
      'Die Wahl beginnt. Es ist anonym, also atmet ruhig weiter.',
      'Zeit zu entscheiden. {count} Kandidaten und keine falsche Antwort. Nur unbequeme.',
    ],
    bissig: [
      'Voting offen. {count} Kandidaten. Ihr wisst, was zu tun ist, und auch mit wem.',
      'Die Abstimmung läuft. {count} Namen. Jetzt zeigt sich, wer Freunde hat und wer Sitznachbarn.',
      'Handys raus. {count} Kandidaten, Begründung Pflicht. Ausreden sind keine Begründung.',
      'Es ist anonym. Das heißt: Ihr könnt jetzt endlich ehrlich sein.',
      '{count} zur Auswahl. Wählt nach Leistung, nach Gefühl oder nach altem Groll. Mir egal.',
      'Voting offen. Denkt daran: Der Beste wird gern zuerst entsorgt.',
      '{count} Kandidaten und eine sehr aufschlussreiche Minute vor euch.',
      'Die Wahl läuft. Ich lese die Begründungen später vor. Alle. Laut.',
      'Zeit für Demokratie. Die unangenehme Sorte, mit Namen und Nachwirkungen.',
    ],
    gnadenlos: [
      'Voting offen. {count} Kandidaten. Sucht euch ein Opfer und schreibt etwas Schönes dazu.',
      'Die Abstimmung läuft. {count} Namen, null Loyalität. Wir kennen das Spiel.',
      'Jetzt wird verraten. {count} Kandidaten, und irgendwer hat es sich redlich verdient.',
      'Handys raus. Anonymität ist das Beste, was der Freundschaft je passiert ist.',
      '{count} zur Wahl. Keine Sorge, ich lese die härtesten Begründungen vor. Genüsslich.',
      'Voting offen. Denkt kurz nach, wen ihr am wenigsten vermissen werdet.',
      'Ihr habt {count} Optionen. Fast alle davon sind Verrat, eine ist Strategie.',
      'Die Wahl beginnt. Bitte lächelt die Person an, die ihr gerade anklickt.',
      '{count} Namen auf dem Schirm. Einer davon ist gleich Vergangenheit.',
    ],
  },

  // {missing} = Zahl der fehlenden Stimmen
  votingSlow: {
    charmant: [
      'Es fehlen noch {missing} Stimmen. Nehmt euch Zeit, aber nicht zu viel.',
      '{missing} von euch grübeln noch. Das ist ein gutes Zeichen für eure Herzen.',
      'Noch {missing} Stimmen offen. Der Rest wartet geduldig. Halbwegs geduldig.',
      'Wir warten auf {missing} Entscheidungen. Ich weiß, es fällt schwer.',
      '{missing} Handys sind noch still. Alles gut, aber die Uhr läuft.',
      'Es fehlen {missing} Stimmen. Vertraut eurem Bauchgefühl, das ist schneller.',
      'Noch {missing} offen. Niemand wird euch später danach fragen, versprochen.',
      '{missing} Stimmen fehlen. Ein Klick, ein Satz, fertig.',
      'Wir brauchen noch {missing} Voten. Der Abend hat noch viel vor.',
    ],
    bissig: [
      'Noch {missing} Stimmen fehlen. Ich sehe genau, wer hier auf Zeit spielt.',
      '{missing} Leute haben noch nicht abgestimmt. Das Gewissen ist ein langsames Organ.',
      'Es fehlen {missing} Stimmen. Enthaltung ist auch eine Antwort. Eine feige.',
      '{missing} Handys schweigen noch. Ihr wisst, dass ich mitzähle, oder?',
      'Noch {missing} offen. Die Person, auf die ihr wartet, wartet auch auf euch.',
      '{missing} Stimmen fehlen. Es ist anonym. Es ist wirklich anonym. Traut euch.',
      'Wir hängen bei {missing} Stimmen fest. Denken im Zeitfenster war noch nie eure Stärke.',
      'Noch {missing} Voten. Für Leute, die sich nicht entscheiden können, habe ich eigene Sprüche.',
      '{missing} fehlen. Der Timer ist ungefähr so nachsichtig wie ich.',
    ],
    gnadenlos: [
      'Noch {missing} Stimmen. Ich notiere jede Sekunde des Zögerns. Für später.',
      '{missing} Feiglinge halten das Studio auf. Ihr wisst, wer gemeint ist.',
      'Es fehlen {missing} Stimmen. Rückgrat ist offenbar Mangelware in diesem Raum.',
      '{missing} Leute können sich nicht entscheiden. Ich kann mich hervorragend entscheiden.',
      'Noch {missing} offen. Wer sich enthält, stimmt in Wahrheit für das eigene Ende.',
      '{missing} Stimmen fehlen. Ich habe Zeit. Der Timer nicht.',
      'Wir warten auf {missing} Personen. Die Nachwelt wartet auch, aber weniger geduldig.',
      '{missing} haben noch nicht geklickt. Jede Sekunde macht euch verdächtiger.',
      'Noch {missing} Stimmen. Ich habe Kontinente sich schneller bewegen sehen.',
    ],
  },

  // keine Platzhalter
  voteReveal: {
    charmant: [
      'Die Stimmen sind ausgezählt. Bitte alle einmal tief durchatmen.',
      'Die Auszählung ist durch. Egal wie es ausgeht: Ihr wart großartig.',
      'Die Karten liegen auf dem Tisch. Ich mache das jetzt so sanft wie möglich.',
      'Alle Stimmen sind da. Ich lese sie euch vor, ganz in Ruhe.',
      'Die Entscheidung ist gefallen. Haltet euch kurz gegenseitig die Hände.',
      'Auszählung beendet. Was jetzt kommt, ist nur ein Spiel. Denkt daran.',
      'Die Stimmen liegen mir vor. Ich mache es kurz und schmerzarm.',
      'Fertig ausgezählt. Vorhang auf für die schwierigste Minute des Abends.',
      'Alle haben gewählt. Jetzt sehen wir, wie sich eure Herzen entschieden haben.',
    ],
    bissig: [
      'Die Stimmen sind ausgezählt. Und sie sind aufschlussreich.',
      'Auszählung fertig. Selten so viel Ehrlichkeit auf so wenig Platz gesehen.',
      'Die Karten liegen. Manche von euch werden gleich überrascht sein. Zu Unrecht.',
      'Alles gezählt. Freundschaften wurden getestet. Das Ergebnis folgt.',
      'Die Stimmen sind da. Wer jetzt nervös lächelt, hat vermutlich recht damit.',
      'Ausgezählt. Ich verlese nun das Ergebnis eurer sogenannten Solidarität.',
      'Die Wahl ist entschieden. Jemand hier hat gerade sehr viele Freunde verloren.',
      'Zählung beendet. Musik leiser, Puls höher.',
      'Alle Stimmen liegen vor. Die Mathematik war eindeutiger als eure Ausreden.',
    ],
    gnadenlos: [
      'Die Stimmen sind ausgezählt. Der Verrat hat ein Ergebnis.',
      'Auszählung beendet. Was ich hier lese, wünscht man niemandem. Also lese ich es vor.',
      'Die Karten liegen. Mindestens eine Person hat sich hier sehr in ihren Freunden geirrt.',
      'Fertig. Ich halte das Ergebnis in der Hand und es ist herrlich unangenehm.',
      'Die Stimmen sind da. Ab jetzt gilt: Wer lächelt, hat es noch nicht begriffen.',
      'Ausgezählt. Zeit, jemanden mit der Wahrheit über seine Beliebtheit zu konfrontieren.',
      'Die Wahl ist entschieden. Ich liebe diesen Teil, ihr hasst ihn. Perfekte Balance.',
      'Alles gezählt. Einer von euch hat gerade seinen letzten Satz gesagt.',
      'Die Stimmen liegen vor. Licht runter, Herzen raus.',
    ],
  },

  // {reason} = Begründungstext, {target} = Name der genannten Person
  readReason: {
    charmant: [
      'Jemand schreibt über {target}: {reason}. Das war fast liebevoll formuliert.',
      'Zu {target} heißt es hier: {reason}. Ein bisschen wahr, ein bisschen fies.',
      'Ich lese vor: {reason}. Gemeint ist {target}. Kopf hoch.',
      'Eine Begründung für {target}: {reason}. Immerhin ehrlich.',
      '{reason}. So steht es hier über {target}. Anonym, aber mit Herz.',
      'Hier schreibt jemand: {reason}. {target}, du darfst das ein wenig persönlich nehmen.',
      'Für {target} wurde notiert: {reason}. Netter ging es offenbar gerade nicht.',
      'Eine Stimme sagt zu {target}: {reason}. Ich finde das erstaunlich diplomatisch.',
      'Anonym eingereicht: {reason}. Betroffen ist {target}. Wir bleiben trotzdem freundlich.',
    ],
    bissig: [
      'Über {target} steht hier: {reason}. Kurz, präzise, vernichtend.',
      'Zitat: {reason}. Gemeint ist {target}. Ich hätte es nicht besser sagen können.',
      '{reason}. Das ging an {target}. Und es sitzt.',
      'Jemand begründet {target} so: {reason}. Beobachtungsgabe kann man euch nicht absprechen.',
      'Hier steht: {reason}. {target}, jemand hat dich sehr genau angeschaut.',
      'Anonym über {target}: {reason}. Anonymität macht Menschen ehrlich und ein bisschen böse.',
      'Eine Begründung, die mir gefällt: {reason}. Zielperson: {target}.',
      '{target} bekommt Folgendes serviert: {reason}. Guten Appetit.',
      'Zu {target} wurde geschrieben: {reason}. Und niemand hat widersprochen.',
    ],
    gnadenlos: [
      'Über {target} schreibt jemand: {reason}. Das ist keine Begründung, das ist ein Nachruf.',
      '{reason}. Das ging an {target}. Ich lese es zweimal, weil es so gut ist.',
      'Hier steht über {target}: {reason}. Diese Person kannte dich zu gut, {target}.',
      'Zitat des Abends, gerichtet an {target}: {reason}.',
      'Anonym, aber tödlich: {reason}. Es geht um {target}.',
      '{target}, jemand hat über dich geschrieben: {reason}. Das musst du dir jetzt merken.',
      'Ich lese ungern Gemeinheiten vor. Ausnahme: {reason}. Betroffen ist {target}.',
      'Die Begründung zu {target} lautet: {reason}. Irgendwo im Raum sitzt jemand und grinst.',
      '{reason}. Wer auch immer das über {target} geschrieben hat: gute Arbeit.',
    ],
  },

  // {names} = die gleichauf liegenden Namen
  tiebreak: {
    charmant: [
      'Gleichstand zwischen {names}. Ein Blitz-Stechen entscheidet. Viel Glück euch beiden.',
      '{names} liegen gleichauf. Jetzt zählt der schnellere Kopf.',
      'Patt bei {names}. Wir klären das freundlich, aber schnell.',
      'Unentschieden: {names}. Eine Frage, ein Sieger. Bleibt locker.',
      '{names} teilen sich den Platz. So kann das nicht bleiben. Stechen!',
      'Gleichstand. {names}, ihr habt euch das gegenseitig eingebrockt.',
      'Es steht unentschieden zwischen {names}. Wer zuerst richtig liegt, bleibt.',
      '{names} sind gleichauf. Ein sauberes Duell entscheidet.',
      'Punktgleich: {names}. Ich mag Stechen. Alle mögen Stechen.',
    ],
    bissig: [
      'Gleichstand zwischen {names}. Ihr seid sogar beim Versagen ein Team.',
      '{names} haben gleich viele Stimmen. Blitz-Stechen. Jetzt wird es unangenehm.',
      'Patt bei {names}. Der Raum konnte sich nicht entscheiden, ich helfe nach.',
      'Unentschieden zwischen {names}. Eine Frage. Wer patzt, geht.',
      '{names}, ihr habt exakt gleich viele Feinde. Das ist fast romantisch.',
      'Gleichstand. {names}, einer von euch war offenbar nicht unbeliebt genug.',
      'Punktgleich: {names}. Wir lösen das mit Wissen statt Sympathie. Ungewohnt für euch.',
      '{names} liegen gleichauf. Der Schnellere bleibt, der andere winkt.',
      'Ein Patt. {names}, jetzt entscheidet ausnahmsweise mal euer Gehirn.',
    ],
    gnadenlos: [
      'Gleichstand zwischen {names}. Zwei Kandidaten, ein Abgrund, eine Frage.',
      '{names}. Gleich viele Stimmen, gleich wenig Rückhalt. Stechen.',
      'Patt bei {names}. Der Raum wollte euch beide loswerden. Leider geht nur einer.',
      'Unentschieden. {names}, ihr duelliert euch jetzt um das Privileg zu bleiben.',
      '{names} sind gleichauf. Einer von euch ist gleich nur noch eine Anekdote.',
      'Gleichstand. Ich hätte euch beide genommen, aber die Regeln sind großzügiger als ich.',
      '{names}, eine Frage trennt euch von der Tür. Enttäuscht mich nicht beide.',
      'Punktgleich: {names}. Ihr habt es geschafft, gleichzeitig zu enttäuschen. Respekt.',
      'Stechen zwischen {names}. Schnell, hart und mit garantiertem Verlierer.',
    ],
  },

  // {name} = Rausgeflogener, {votes} = Stimmen gegen ihn,
  // {correct} = richtige Antworten, {total} = Fragen der Runde
  elimination: {
    charmant: [
      '{name}, {votes} Stimmen. Du gehst mit erhobenem Kopf und {correct} von {total} im Gepäck.',
      'Der Raum hat entschieden: {name}. Viel Sympathie, trotzdem die Tür. Du fliegst!',
      '{name}, du hast {correct} von {total} geschafft und dabei durchgehend gelächelt. Das rechne ich hoch an.',
      'Es tut mir aufrichtig leid. {votes} Stimmen sind {votes} zu viel. {name}, du fliegst!',
      'Bahnhofsdurchsage: Der Zug in Richtung Feierabend fährt mit {name} ab.',
      '{name}, du warst der freundlichste Mensch auf dieser Bühne. Leider zählt das nicht.',
      'Wetterbericht: heiter mit {votes} Stimmen gegen {name}. Örtlich Tränen.',
      'Mit {correct} von {total} Treffern verlässt du das Studio, {name}. Erhobenen Hauptes.',
      'Jede Show braucht einen, der zu früh gehen muss. Heute bist du dieser Held, {name}.',
      'Die Stimmen sagen {name}. Mein Herz sagt: schade. Du fliegst!',
      'Servicehinweis: {name} verlässt die Bühne. Bitte kräftig applaudieren.',
      '{name}, {votes} Stimmen. Immerhin haben sich alle die Mühe gemacht, dich zu meinen.',
      'Du gehst als Sympathieträger, {name}. Das ist mehr wert als der halbe Pott. Fast.',
      '{correct} von {total}, {name}. Das ist keine Schande, das ist ein solider Abend.',
      '{name}, du hast heute mehr gelacht als alle anderen. Nimm das mit. Du fliegst!',
      'Ein letztes Mal Spotlight für {name}. Genieß es, du hast es dir verdient.',
      'Ein Rausschmiss ist nur ein Ortswechsel, {name}. Ein sehr lautstarker.',
      '{name}, {votes} Menschen haben deinen Namen geschrieben. Sie werden dich vermissen.',
      'Danke für {correct} richtige Antworten, {name}. Und danke fürs Mitspielen. Du fliegst!',
      'Die Tür geht auf und {name} geht hindurch. Vorsichtig, es ist kalt draußen.',
      '{name}, du warst der Kitt dieser Gruppe. Der Kitt fliegt jetzt raus.',
      'Manchmal trifft es die Falschen. Heute trifft es {name}. Du fliegst!',
      '{name}, du hattest {correct} von {total} und hundert Prozent Anstand.',
      'Wir verabschieden {name} mit warmem Applaus und leisem Bedauern.',
      '{votes} Stimmen für {name}. Es war knapp, es war fair, es ist vorbei.',
      '{name}, du machst Platz für andere. Die höflichste Art zu verlieren.',
      'Das Schicksal hat einen Namen gezogen und der lautet {name}. Kein Grund zu hadern.',
      '{name}, ich hätte dich gern behalten. Die Demokratie sieht das anders. Du fliegst!',
      'Mit {correct} von {total} und einem guten Herzen verlässt du uns, {name}.',
      'Nächster Halt für {name}: Geisterzone. Es soll dort Snacks geben.',
      '{name}, du hast keinen einzigen Streit angefangen. Vorbildlich. Und trotzdem: Du fliegst!',
      'Die Gruppe hat gewählt. {votes} Stimmen für {name}, dazu ein leicht schlechtes Gewissen.',
    ],
    bissig: [
      '{name}, {votes} Stimmen. Deine Freunde haben abgestimmt und sie waren sich einig.',
      '{correct} von {total}. {name}, das ist keine Bilanz, das ist ein Hilferuf. Du fliegst!',
      'Ergebnis der Abstimmung: {name} mit {votes} Stimmen. Kein Einspruch möglich.',
      'Sportreporter-Modus: {name} verlässt das Feld. Ohne Auswechslung, ohne Applaus.',
      '{name}, du hast {correct} von {total} getroffen. Der Rest war freie Interpretation.',
      'Behördlich festgestellt: Antrag von {name} auf Verbleib abgelehnt. {votes} Stimmen dagegen.',
      '{name}, du warst heute so präsent wie ein Funkloch. Du fliegst!',
      'Die Gruppe hat gesprochen. Laut. Und sie hat {name} gesagt.',
      '{votes} Stimmen, {name}. Beliebtheit war noch nie deine Kernkompetenz.',
      'Wetterdienst meldet für {name}: Sturmböen von hinten, Reiserichtung Ausgang.',
      '{name}, {correct} richtige Antworten. Ich kenne Zufallsgeneratoren mit besserer Quote.',
      'Der Raum wollte dich loswerden, {name}, und der Raum bekommt, was er will. Du fliegst!',
      'Serviceansage: Der Sitzplatz von {name} wird ab sofort neu vergeben.',
      '{name}, du warst nicht der Schlechteste. Nur der Auffälligste.',
      'Bei {votes} Stimmen gegen dich, {name}, wäre selbst eine Neuwahl sinnlos.',
      '{name}, {correct} von {total}. Ich runde das aus reiner Höflichkeit nicht.',
      'Es war eine kurze, aber lehrreiche Zeit, {name}. Lehrreich vor allem für uns.',
      'Deine Freunde haben dich gewählt, {name}. Nur leider nicht zum Bleiben. Du fliegst!',
      '{name}, die Statistik hat dich verraten, lange bevor die Stimmen es taten.',
      'Auf dem Zeugnis von {name} steht: bemüht sich. Mehr steht da nicht.',
      '{votes} Stimmen. {name}, das war kein Voting, das war ein Volksentscheid.',
      '{name}, dein Beitrag zum Pott passt bequem in einen Fingerhut. Du fliegst!',
      'Die Tür kennt jetzt deinen Namen, {name}. Sie merkt ihn sich besser als du die Antworten.',
      '{name}, {correct} von {total}, und jede falsche mit voller Überzeugung.',
      'Anonyme Abstimmung, eindeutiges Ergebnis: {name}. Demokratie kann effizient sein.',
      '{name}, du hast heute vor allem eines bewiesen: Anwesenheit. Du fliegst!',
      'Der Pott bleibt hier, {name}. Du nicht.',
      'Applaus für {name}, mit {votes} Stimmen der eindeutigste Fall des Abends.',
      '{name}, ich habe dich gemocht. Der Rest des Raumes offenbar nur in Maßen.',
      'Von {total} Fragen hast du {correct} gelöst, {name}. Der Rest hat dich gelöst.',
      '{name}, das war keine knappe Entscheidung. Das war ein Konsens. Du fliegst!',
      'Letzter Aufruf für {name}. Es wird keinen weiteren geben.',
    ],
    gnadenlos: [
      '{name}, {votes} Stimmen. Selten war sich eine Gruppe so schnell so einig. Du fliegst!',
      '{correct} von {total}. {name}, ich habe das dreimal geprüft. Es wird nicht besser.',
      'Nachruf auf {name}: geliebt von wenigen, gewählt von {votes}.',
      '{name}, dein Wissen war heute ein Gerücht. Du fliegst!',
      'Amtliche Bekanntmachung: Die Anwesenheit von {name} wird mit sofortiger Wirkung eingestellt.',
      '{name}, du hast {correct} Fragen richtig beantwortet. {votes} Leuten war das zu wenig.',
      'Naturdoku: Wir beobachten {name}, ein Exemplar, das sich vom Rudel trennt. Unfreiwillig.',
      '{name}, dieser Raum hat abgestimmt wie ein Mann. Und der Mann mochte dich nicht.',
      'Beipackzettel für {name}: Nebenwirkungen waren Frust, Kettenbrüche und {votes} Stimmen.',
      '{name}, du hast das Studio betreten wie ein Held und verlässt es als Randnotiz.',
      '{correct} von {total}, {name}. Ich kenne Toaster, die entschlossener geantwortet haben.',
      'Die Abstimmung war kein Wettkampf, {name}. Sie war eine Formalität. Du fliegst!',
      '{name}, du wurdest nicht rausgewählt. Du wurdest entsorgt.',
      'Wetterlage über {name}: {votes} Stimmen aus allen Richtungen, keine Besserung in Sicht.',
      '{name}, dein größter Beitrag heute war das Verkürzen der Kette.',
      'Der Stuhl von {name} wird jetzt desinfiziert und neu vergeben. Du fliegst!',
      '{name}, {votes} Stimmen. Das ist keine Niederlage, das ist ein Erdrutsch.',
      'Kochshow: Wir nehmen {name}, entfernen alle Punkte und servieren den Rest der Geisterzone.',
      '{name}, du hattest {total} Chancen und {correct} davon genutzt. Der Rest war Deko.',
      'Man wird sich an dich erinnern, {name}. Kurz. Und ungern. Du fliegst!',
      '{name}, {votes} Menschen haben deinen Namen getippt. Nicht einer hat gezögert.',
      'IT-Support meldet: Die Verbindung zu {name} wurde nicht getrennt, sondern gekappt.',
      '{name}, du warst der Beweis, dass Selbstvertrauen und Kompetenz getrennte Konzepte sind.',
      'Reisehinweis für {name}: einfache Fahrt, keine Rückfahrkarte, Abflug sofort. Du fliegst!',
      '{correct} von {total}. {name}, diese Zahl begleitet dich noch eine Weile.',
      '{name}, deine Mitspieler haben schneller entschieden, als du je geantwortet hast.',
      'Es gibt Momente, die man festhalten möchte. Dieser ist einer. {name}, du fliegst!',
      '{name}, {votes} Stimmen und kein einziger Fürsprecher. Beeindruckend geschlossen.',
      'Der Pott hat dich nie gekannt, {name}, und er wird dich nicht vermissen.',
      '{name}, du gehst als der Grund, warum diese Runde Nerven gekostet hat. Du fliegst!',
      'Ich habe eine gute und eine schlechte Nachricht, {name}. Die gute ist für die anderen.',
      'Spotlight auf {name}. Letztes Bild, letzter Satz, letzte Sekunde. Du fliegst!',
    ],
  },

  // {name} = Rausgeflogener, {correct} = richtige Antworten, {total} = Fragen der Runde
  eliminationTop: {
    charmant: [
      '{name}, {correct} von {total} und trotzdem raus. Das ist das Kompliment der Woche.',
      'Der beste Spieler der Runde geht: {name} mit {correct} Treffern. Kopf hoch, du warst zu gut.',
      '{name}, du warst zu stark. Die anderen hatten Angst. Nimm das als Sieg mit.',
      'Mit {correct} von {total} verlässt uns die Nummer eins. {name}, das war unfair und schön.',
      '{name}, so verliert man nicht. So wird man weggelobt.',
      'Die Bestenliste sagt {name}. Die Stimmen sagen: raus. Beides stimmt.',
      '{name}, {correct} richtige Antworten und ein Rauswurf. Das nennt man Respekt in Handschellen.',
      'Du gehst als Bester, {name}. Die eleganteste Art zu fliegen.',
      '{name}, du hast alles richtig gemacht. Außer unauffällig zu sein.',
    ],
    bissig: [
      '{name}, {correct} von {total}. Beste Leistung, erster Rauswurf. Willkommen in der Demokratie.',
      'Der stärkste Spieler fliegt. {name}, deine Kompetenz war dein Urteil.',
      '{name} mit {correct} Treffern. Zu gut zum Behalten, zu gefährlich fürs Finale.',
      'Glückwunsch, {name}, du warst der Beste. Deshalb bist du jetzt der Erste an der Tür.',
      '{name}, {correct} von {total}. Die anderen konnten nicht mithalten, also haben sie gewählt.',
      'Taktik schlägt Talent. {name}, du bist der lebende Beweis.',
      '{name}, du warst die Bedrohung. Bedrohungen werden entfernt, nicht bewundert.',
      'Beste Quote der Runde, schlechteste Umfragewerte. {name}, das ist Politik.',
      '{name} geht mit {correct} von {total}. Manchmal ist Können einfach eine Zielscheibe.',
    ],
    gnadenlos: [
      '{name}, {correct} von {total} und trotzdem raus. Willkommen in einer Welt, die Talent bestraft.',
      'Der Beste fliegt zuerst. {name}, das ist keine Ungerechtigkeit, das ist Strategie mit Messer.',
      '{name}, deine {correct} Treffer waren dein eigenes Urteil. Sauber erarbeitet, sauber erledigt.',
      'Sie haben dich nicht rausgewählt, weil du schlecht warst, {name}. Sondern weil sie Angst hatten.',
      '{name}, {correct} von {total}. Genug, um zu gewinnen. Zu viel, um zu überleben.',
      'Den Stärksten zu entfernen nennt man anderswo Feigheit. Hier nennt man es Spielzug, {name}.',
      '{name}, du warst die beste Antwortmaschine im Raum und die schlechteste Wahl für alle anderen.',
      'Mit {correct} Treffern wirst du zur Legende, {name}. Legenden sind übrigens immer weg.',
      '{name}, dein Können hat dich verraten, lange bevor deine Freunde es taten.',
    ],
  },

  // {name} = frisch rausgeflogener Spieler
  ghostWelcome: {
    charmant: [
      'Willkommen in der Geisterzone, {name}. Hier gibt es Ruhe, Aussicht und keine Fragen.',
      '{name}, du bist jetzt Geist. Das heißt: alle Rechte, keine Verantwortung.',
      'Plopp. {name} ist angekommen. Mach es dir gemütlich.',
      'Die Geisterzone freut sich über {name}. Von hier oben sieht alles entspannter aus.',
      '{name}, ab jetzt darfst du zuschauen und lästern. Beides ist ausdrücklich erlaubt.',
      'Willkommen, {name}. Als Geist kannst du wetten, jubeln und niemanden mehr enttäuschen.',
      '{name} schwebt jetzt mit uns. Es gibt schlimmere Schicksale.',
      'Geisterzone, Neuzugang {name}. Bitte einmal freundlich buhen, alle zusammen.',
      '{name}, du bist raus, aber nicht weg. Genau so soll das sein.',
    ],
    bissig: [
      'Willkommen in der Geisterzone, {name}. Hier wird nicht mehr gefragt, nur noch gemeckert.',
      '{name}, als Geist bist du endlich zu etwas nütze: Publikum.',
      'Die Geisterzone hat einen neuen Bewohner. {name}, links der Chat, rechts die Bitterkeit.',
      '{name}, ab jetzt kannst du alles besser wissen. Ohne Konsequenzen. Dein Traumjob.',
      'Plopp. {name} ist jetzt durchsichtig. Passt farblich zur bisherigen Leistung.',
      'Willkommen unter den Untoten, {name}. Buhen ist Pflicht, Fragen sind verboten.',
      '{name} betritt die Geisterzone. Endlich ein Ort, an dem Punkte egal sind.',
      'Geisterzone für {name}. Hier kannst du behaupten, du hättest es gewusst. Unprüfbar.',
      '{name}, du bist nun Zuschauer. Ein emotional stark beteiligter Zuschauer.',
    ],
    gnadenlos: [
      '{name} materialisiert in der Geisterzone. Der Übergang war schmerzhafter für dich als für uns.',
      'Willkommen im Jenseits des Quiz, {name}. Hier hört dich niemand raten.',
      '{name}, du bist jetzt ein Geist. Also das, was du im Spiel ohnehin schon warst.',
      'Die Geisterzone nimmt {name} auf. Sie nimmt jeden. Das ist ihr Problem.',
      '{name}, hier oben darfst du zusehen, wie andere das schaffen, was du versucht hast.',
      'Plopp. Ein neues Gespenst namens {name}. Buht es an, es hat es verdient.',
      '{name}, ab sofort bist du Statistik mit Meinung.',
      'Willkommen, {name}. In der Geisterzone kann man nicht verlieren. Das hast du vorher erledigt.',
      '{name} ist jetzt Geist. Ein Applaus für den Übergang, er war kurz und endgültig.',
    ],
  },

  // {a}, {b} = Finalisten, {pot} = Pott
  finalIntro: {
    charmant: [
      'Das Finale: {a} gegen {b}. Der Pott bei {pot} wartet auf einen von euch.',
      '{a} und {b} haben es geschafft. Alles andere ist ab jetzt egal.',
      'Zwei bleiben übrig: {a} und {b}. Es geht um {pot} und um alles.',
      'Applaus für {a} und {b}. Ihr habt euch hierher gekämpft, fair und mit Herz.',
      'Der Pott steht bei {pot}. Auf der Bühne stehen {a} und {b}. Möge der Bessere gewinnen.',
      '{a} gegen {b}. Egal wie es ausgeht, ihr beide wart heute stark.',
      'Das große Finale. {a}, {b}, tief durchatmen. Es geht um {pot}.',
      'Zwei Namen, ein Pott von {pot}: {a} und {b}. Zeigt es uns.',
      'Finale. {a} und {b}, ihr habt euch das verdient. Viel Glück euch beiden.',
    ],
    bissig: [
      'Finale: {a} gegen {b}. Zwei Überlebende, ein Pott von {pot}, ab jetzt null Freundschaft.',
      '{a} und {b} im Finale. Nicht weil sie die Besten sind, sondern weil sie kaum auffielen.',
      'Der Pott bei {pot} gehört gleich einem von euch. Der andere bekommt Erinnerungen.',
      '{a} gegen {b}. Alle anderen dürfen jetzt zusehen und bereuen.',
      'Zwei sind übrig. {a}, {b}: Ab hier hilft kein Voting mehr, nur noch Wissen.',
      'Das Finale um {pot}. {a} und {b}, ihr habt euch gegenseitig verschont. Das endet jetzt.',
      '{a} und {b} im Duell. Die Geister in der Zone haben schon Wetten laufen.',
      'Finale. {pot} im Pott. Einer geht als Sieger, einer als Fußnote.',
      '{a} gegen {b}. Ich mag Duelle. Besonders, wenn beide nervös sind.',
    ],
    gnadenlos: [
      'Finale: {a} gegen {b}. Zwei Menschen, ein Pott von {pot}, kein Platz für den Zweiten.',
      '{a} und {b}. Ihr habt euch durch Verrat hierher gearbeitet. Macht es unter euch aus.',
      'Der Pott bei {pot} sucht einen Besitzer. Der Verlierer bekommt nichts. Wirklich nichts.',
      '{a} gegen {b}. Blitz-Duell. Wer zögert, verliert alles.',
      'Zwei stehen noch. {a}, {b}, einer wird gleich sehr laut über sich selbst nachdenken.',
      'Finale um {pot}. {a} und {b}, ab hier zählt kein Charme mehr, nur Reaktionszeit.',
      '{a} und {b}. Alle, die euch hierher gelassen haben, bereuen es bereits.',
      'Das Endspiel. {pot} auf dem Tisch, zwei Namen an der Wand, gleich nur noch einer.',
      '{a} gegen {b}. Ein Duell, das niemand ungeschoren übersteht.',
    ],
  },

  // {name} = Punktgewinner, {scoreA}, {scoreB} = Punktestand
  finalPoint: {
    charmant: [
      'Punkt für {name}. Es steht {scoreA} zu {scoreB}. Spannend bleibt es.',
      '{name} holt den Punkt. {scoreA} zu {scoreB}, der Abend hat noch Luft.',
      'Sauber gemacht, {name}. Zwischenstand {scoreA} zu {scoreB}.',
      'Der Punkt geht an {name}. Es steht {scoreA} zu {scoreB}, alles offen.',
      '{name} war schneller. {scoreA} zu {scoreB}. Bleibt beide ruhig.',
      'Ein Treffer für {name}. Das Tauziehen steht bei {scoreA} zu {scoreB}.',
      'Das war stark, {name}. Der Stand lautet {scoreA} zu {scoreB}.',
      'Punkt, {name}. {scoreA} zu {scoreB}. Das ist ein schönes Finale.',
      '{name} macht den Punkt. Der Stand: {scoreA} zu {scoreB}.',
    ],
    bissig: [
      'Punkt für {name}. {scoreA} zu {scoreB}. Der andere darf jetzt kurz schwitzen.',
      '{name} war schneller. {scoreA} zu {scoreB}. Reaktionszeit schlägt Selbstbewusstsein.',
      'Der Punkt geht an {name}. Stand {scoreA} zu {scoreB}, und die Nerven liegen frei.',
      '{name} holt sich das. {scoreA} zu {scoreB}. Man sieht, wer geübt hat.',
      'Treffer, {name}. {scoreA} zu {scoreB}. Der Pott rückt näher an einen Namen.',
      '{scoreA} zu {scoreB} nach dem Punkt von {name}. Es wird ungemütlich.',
      '{name} punktet. Das Gegenüber überdenkt gerade ein paar Lebensentscheidungen.',
      'Ein Punkt für {name}. {scoreA} zu {scoreB}. Wer jetzt patzt, geht als Zweiter heim.',
      '{name} liefert. {scoreA} zu {scoreB}. Die Geisterzone tobt.',
    ],
    gnadenlos: [
      'Punkt für {name}. {scoreA} zu {scoreB}. Der andere spürt gerade, wie Zeit sich anfühlt.',
      '{name} schlägt zu. {scoreA} zu {scoreB}. Das war kein Duell, das war ein Übergriff.',
      'Treffer, {name}. Stand {scoreA} zu {scoreB}. Ich rieche Panik und sie riecht gut.',
      '{name} nimmt den Punkt. {scoreA} zu {scoreB}. Der Pott hat sich wohl entschieden.',
      '{scoreA} zu {scoreB}. {name} führt das Messer, der andere hält still.',
      'Punkt für {name}. Jede Sekunde Zögern kostet gerade sichtbar Substanz.',
      '{name} war schneller. {scoreA} zu {scoreB}. Schnelligkeit ist die grausamste Tugend.',
      'Ein Punkt für {name}. Der Gegner hat gerade seine letzte Ausrede aufgebraucht.',
      '{scoreA} zu {scoreB} durch {name}. Es wird knapp. Es wird brutal.',
    ],
  },

  // {name} = Spieler mit Matchball
  matchPoint: {
    charmant: [
      'Matchball für {name}. Ein Treffer und es ist geschafft.',
      '{name} steht einen Punkt vor dem Sieg. Ruhig bleiben, es ist fast vorbei.',
      'Matchball. {name}, du brauchst nur noch eine richtige Antwort.',
      '{name} hat den Matchball. Der Rest ist Nervensache.',
      'Ein Punkt trennt {name} vom Titel. Atmet alle einmal durch.',
      'Matchball für {name}. Das Publikum steht, zumindest im übertragenen Sinne.',
      '{name}, du bist einen Schritt entfernt. Einen einzigen Schritt.',
      'Es ist Matchball. {name}, das schaffst du.',
      'Nur noch ein Punkt für {name}. Was für ein Finale.',
    ],
    bissig: [
      'Matchball für {name}. Ein Punkt trennt dich vom Ruhm, den anderen von der Erklärungsnot.',
      '{name} hat Matchball. Jetzt bitte nicht das machen, was ihr sonst so macht.',
      'Ein Punkt bis zum Sieg, {name}. Das ist der Moment, in dem Hände zittern.',
      'Matchball. {name}, du kannst das gewinnen oder sehr spektakulär vergeben.',
      '{name} steht vor dem Titel. Die Geisterzone hält den Atem an, aus reiner Sensationslust.',
      'Matchball für {name}. Der andere hofft jetzt auf ein Wunder. Wunder sind selten.',
      'Ein Treffer, {name}, und der Pott gehört dir. Kein Druck.',
      '{name} hat Matchball. Ich habe hier schon Leute scheitern sehen. Viele.',
      'Matchball. {name}, jetzt zählt nur noch, ob dein Kopf mitspielt.',
    ],
    gnadenlos: [
      'Matchball für {name}. Ein Punkt und alles war umsonst. Für den anderen.',
      '{name} steht am Abgrund des Sieges. Ein Schritt vor, ein Leben lang Angeberei.',
      'Matchball. {name}, jetzt wäre ein schlechter Zeitpunkt für Menschlichkeit.',
      'Ein Punkt trennt {name} vom Pott. Und den anderen von der ewigen zweiten Stelle.',
      'Matchball für {name}. Der Gegner rechnet gerade aus, wie er das erklären soll.',
      '{name}, ein Treffer und du beendest das hier. Zeig kein Erbarmen.',
      'Matchball. Ich habe an dieser Stelle schon Nervenzusammenbrüche live begleitet.',
      '{name} braucht einen Punkt. Der andere braucht ein Wunder und ein neues Gedächtnis.',
      'Matchball für {name}. Ab jetzt ist jeder Fehler eine Anekdote für die Ewigkeit.',
    ],
  },

  // {name} = Sieger, {pot} = gewonnener Pott
  victory: {
    charmant: [
      '{name} gewinnt und nimmt {pot} mit. Verdient, sauber, wunderschön.',
      'Die Krone gehört {name}. {pot} Punkte und eine Menge Respekt.',
      '{name}, du hast es geschafft. Der Pott von {pot} ist deiner.',
      'Sieger des Abends: {name}. Konfetti an, Musik laut, {pot} auf dem Konto.',
      'Was für ein Finale. {name} holt den Pott von {pot}. Applaus für alle.',
      '{name} steht ganz oben. {pot} Punkte und ein sehr breites Grinsen.',
      'Herzlichen Glückwunsch, {name}. Du warst der Kopf des Abends. {pot} sind deine.',
      'Der Pott von {pot} geht an {name}. Alle anderen dürfen stolz auf sich sein.',
      '{name} gewinnt. Ein fairer Sieg, ein glücklicher Mensch, {pot} Punkte.',
      'Krone auf, {name}. {pot} Punkte sind der Beweis, dass du das kannst.',
      '{name} ist unser Champion. Bitte einmal alle laut werden.',
      'Der Abend gehört {name}. {pot} Punkte, und niemand kann etwas dagegen sagen.',
      '{name}, du hast die Nerven behalten, als es zählte. {pot} sind der Lohn.',
      'Sieg für {name}. Der Pott von {pot} wechselt den Besitzer, die Freundschaft bleibt.',
      'Wir haben einen Gewinner: {name}. Und einen sehr vollen Pott: {pot}.',
      '{name} nimmt den Pott von {pot} mit nach Hause. Gut gemacht, wirklich.',
    ],
    bissig: [
      '{name} gewinnt {pot}. Der Rest gewinnt Erfahrung. Unbezahlbar und völlig wertlos.',
      'Sieger: {name}. {pot} Punkte, und plötzlich waren alle immer schon auf deiner Seite.',
      '{name} holt den Pott von {pot}. Die anderen holen sich jetzt bitte Ausreden.',
      'Die Krone geht an {name}. Ich hatte auf jemand anderen gesetzt. Gut, dass hier nicht gewettet wird.',
      '{name}, {pot} Punkte. Kaufen kannst du dir davon nichts, erzählen dafür sehr viel.',
      'Champion des Abends: {name}. Wer hätte das gedacht. Außer {name}.',
      '{name} gewinnt. Der Pott von {pot} ist offiziell in den falschen Händen. Glückwunsch.',
      'Sieg für {name}. Die Geisterzone applaudiert mit sehr gemischten Gefühlen.',
      '{pot} Punkte für {name}. Und für alle anderen die stille Frage: warum nicht ich?',
      '{name} steht oben. Alle anderen stehen in der Küche und reden über Pech.',
      'Der Pott von {pot} gehört {name}. Verdient? Sagen wir: rechtmäßig.',
      '{name} gewinnt, und mindestens drei Menschen hier bereuen ihre Stimmabgabe.',
      'Sieger {name}, {pot} im Sack. Bitte einmal bescheiden bleiben. Nur einmal.',
      '{name} nimmt alles mit. Die anderen nehmen den Heimweg.',
      'Der Titel geht an {name}. Ich schreibe das ins Protokoll, damit es niemand bestreitet.',
      '{name} gewinnt {pot}. Ein Hoch auf den Menschen, der am wenigsten Fehler zugegeben hat.',
    ],
    gnadenlos: [
      '{name} gewinnt {pot}. Alle anderen sind ab sofort nur noch Kontext.',
      'Der Pott von {pot} gehört {name}. Der Rest von euch gehört in die Statistik.',
      'Sieger: {name}. Merkt euch dieses Gesicht, es wird euch noch jahrelang begleiten.',
      '{name} steht auf dem Podest. Ihr steht daneben. Das ist der ganze Unterschied.',
      '{pot} Punkte für {name}. Für alle anderen: nichts. Absolut nichts.',
      '{name} hat gewonnen. Nicht wegen des Glücks, sondern weil ihr es nicht besser konntet.',
      'Die Krone fällt auf {name}. Die anderen dürfen jetzt in Ruhe darüber nachdenken.',
      '{name} nimmt {pot} mit. Ihr nehmt eine Lehre mit, die euch niemand abkaufen will.',
      'Champion {name}. Der Abend hatte genau einen Gewinner und sehr viele Beweise dafür.',
      '{name} gewinnt. Und irgendwo sitzt jemand, der ihn hätte rauswählen können. Zu spät.',
      'Der Pott: {pot}. Der Besitzer: {name}. Die Moral: keine.',
      '{name} hat euch alle überstanden. Das ist mehr Leistung als jede richtige Antwort.',
      'Sieg für {name}. Die Geisterzone schweigt. Endlich.',
      '{name} bekommt {pot} und das Recht, das ganze Jahr davon zu reden.',
      'Es gibt heute nur einen Namen und der lautet {name}. Alle anderen sind Beiwerk.',
      '{name} triumphiert. Ich würde gratulieren, aber ihr braucht das Mitleid dringender.',
    ],
  },

  // keine Platzhalter
  rematch: {
    charmant: [
      'Das war ein schöner Abend. Wer will die Revanche?',
      'Noch eine Runde? Die Tür schwingt in beide Richtungen.',
      'Ich hätte Lust auf mehr. Ihr auch? Dann startet einfach neu.',
      'Revanche gefällig? Die Geister warten schon auf ihre zweite Chance.',
      'Eine neue Lobby ist schnell gemacht. Traut euch.',
      'Das war Runde eins eures Abends. Zeit für Runde zwei.',
      'Wer eben rausgeflogen ist, darf jetzt Rache üben. Freundlich, versteht sich.',
      'Nochmal? Ich habe noch jede Menge Fragen und ein paar nette Worte übrig.',
      'Danke fürs Spielen. Und jetzt: Revanche.',
    ],
    bissig: [
      'Revanche? Ich habe noch reichlich Sprüche und ihr noch reichlich Lücken.',
      'Nochmal? Die Ausreden von eben sind noch warm, die könnt ihr wiederverwenden.',
      'Eine neue Runde wäre eure Chance, das hier zu korrigieren. Theoretisch.',
      'Wer sich ungerecht behandelt fühlt, darf jetzt beweisen, dass er recht hatte.',
      'Revanche gefällig? Diesmal vielleicht mit Vorbereitung.',
      'Noch eine Partie? Ich verspreche schwerere Fragen und schlechtere Laune.',
      'Ihr wisst, wo der Startknopf ist. Und ich weiß, wo eure Schwächen sind.',
      'Nochmal spielen? Die Sitzordnung bleibt, die Freundschaften vermutlich nicht.',
      'Revanche. Oder ihr geht mit diesem Ergebnis ins Bett. Eure Entscheidung.',
    ],
    gnadenlos: [
      'Revanche? Ich bin bereit. Ihr wart es heute Abend nie.',
      'Noch eine Runde. Diesmal ohne Anfängerglück, damit wir die Wahrheit sehen.',
      'Wer sich ungerecht behandelt fühlt, darf sich jetzt noch schlimmer blamieren.',
      'Revanche gefällig? Die unangenehmen Fragen habe ich noch gar nicht ausgepackt.',
      'Neue Runde, neue Rauswürfe, gleiche Enttäuschungen. Startet, wann immer ihr wollt.',
      'Nochmal? Ein paar von euch sind zu früh gegangen. Andere blieben viel zu lange.',
      'Ihr könnt es wieder versuchen. Die Statistik spricht dagegen, aber Hoffnung ist billig.',
      'Revanche. Und diesmal wähle ich mit. Im Geiste.',
      'Noch eine Partie? Ich habe Zeit, Sprüche und keinerlei Mitgefühl.',
    ],
  },
};

export default LINES;
