// Kuratierter Offline-Grundstock ("Reservepaket").
// Jede Frage: genau eine unstrittig richtige Antwort, drei klar falsche,
// aber plausible Distraktoren aus derselben Entitätsklasse.
//
// Aufnahmekriterium: nur zeitlich stabile, unstrittige Fakten
// (Jahreszahlen, Urheberschaften, Hauptstädte, Naturkonstanten, Symbole).
// Keine Rekorde mit knappem Abstand, keine Amtsträger, keine Schätzwerte.
export const BANK = [
  // ---------------------------------------------------------------------------
  // ALLGEMEINWISSEN — leicht
  // ---------------------------------------------------------------------------
  {
    id: 'b0001',
    cat: 'allgemeinwissen',
    diff: 'leicht',
    text: 'Wer schrieb die Tragödie „Faust“?',
    options: ['Friedrich Schiller', 'Heinrich Heine', 'Johann Wolfgang von Goethe', 'Thomas Mann'],
    correct: 2,
    fact: 'werk:faust',
  },
  {
    id: 'b0002',
    cat: 'allgemeinwissen',
    diff: 'leicht',
    text: 'Wer malte die „Mona Lisa“?',
    options: ['Leonardo da Vinci', 'Michelangelo', 'Raffael', 'Sandro Botticelli'],
    correct: 0,
    fact: 'werk:mona-lisa',
  },
  {
    id: 'b0003',
    cat: 'allgemeinwissen',
    diff: 'leicht',
    text: 'Wie viele Spieler einer Mannschaft stehen beim Fußball auf dem Feld?',
    options: ['9', '10', '12', '11'],
    correct: 3,
    fact: 'sport:fussball-spielerzahl',
  },
  {
    id: 'b0004',
    cat: 'allgemeinwissen',
    diff: 'leicht',
    text: 'Wie viele Tasten hat ein modernes Klavier?',
    options: ['76', '88', '92', '64'],
    correct: 1,
    fact: 'musik:klavier-tasten',
  },
  {
    id: 'b0005',
    cat: 'allgemeinwissen',
    diff: 'leicht',
    text: 'Wer komponierte die Oper „Die Zauberflöte“?',
    options: ['Wolfgang Amadeus Mozart', 'Ludwig van Beethoven', 'Joseph Haydn', 'Richard Wagner'],
    correct: 0,
    fact: 'werk:zauberfloete',
  },
  {
    id: 'b0006',
    cat: 'allgemeinwissen',
    diff: 'leicht',
    text: 'In welchem Jahr fiel die Berliner Mauer?',
    options: ['1987', '1988', '1989', '1991'],
    correct: 2,
    fact: 'jahr:mauerfall',
  },
  {
    id: 'b0007',
    cat: 'allgemeinwissen',
    diff: 'leicht',
    text: 'Wie heißt der Kriegsgott der römischen Mythologie?',
    options: ['Jupiter', 'Mars', 'Neptun', 'Merkur'],
    correct: 1,
    fact: 'mythologie:roemischer-kriegsgott',
  },
  {
    id: 'b0008',
    cat: 'allgemeinwissen',
    diff: 'leicht',
    text: 'Wer schrieb das Drama „Romeo und Julia“?',
    options: ['Christopher Marlowe', 'Charles Dickens', 'Oscar Wilde', 'William Shakespeare'],
    correct: 3,
    fact: 'werk:romeo-und-julia',
  },
  {
    id: 'b0009',
    cat: 'allgemeinwissen',
    diff: 'leicht',
    text: 'Welche Farbe entsteht beim Mischen von Blau und Gelb?',
    options: ['Orange', 'Violett', 'Braun', 'Grün'],
    correct: 3,
    fact: 'farbe:blau-plus-gelb',
  },
  {
    id: 'b0010',
    cat: 'allgemeinwissen',
    diff: 'leicht',
    text: 'Wie viele Minuten dauert eine Halbzeit im Fußball?',
    options: ['30', '45', '50', '60'],
    correct: 1,
    fact: 'sport:fussball-halbzeit',
  },
  {
    id: 'b0011',
    cat: 'allgemeinwissen',
    diff: 'leicht',
    text: 'Welcher Vogel ist das Wappentier der USA?',
    options: ['Weißkopfseeadler', 'Steinadler', 'Kondor', 'Truthahn'],
    correct: 0,
    fact: 'symbol:usa-wappentier',
  },
  {
    id: 'b0012',
    cat: 'allgemeinwissen',
    diff: 'leicht',
    text: 'Wer schrieb die Erzählung „Die Verwandlung“?',
    options: ['Thomas Mann', 'Hermann Hesse', 'Franz Kafka', 'Robert Musil'],
    correct: 2,
    fact: 'werk:die-verwandlung',
  },
  {
    id: 'b0013',
    cat: 'allgemeinwissen',
    diff: 'leicht',
    text: 'Wie viele Saiten hat eine gewöhnliche Violine?',
    options: ['3', '4', '5', '6'],
    correct: 1,
    fact: 'musik:violine-saiten',
  },
  {
    id: 'b0014',
    cat: 'allgemeinwissen',
    diff: 'leicht',
    text: 'In welcher Stadt steht das Kolosseum?',
    options: ['Athen', 'Neapel', 'Florenz', 'Rom'],
    correct: 3,
    fact: 'bauwerk:kolosseum-stadt',
  },
  {
    id: 'b0015',
    cat: 'allgemeinwissen',
    diff: 'leicht',
    text: 'Wer malte die Decke der Sixtinischen Kapelle?',
    options: ['Michelangelo', 'Raffael', 'Leonardo da Vinci', 'Tizian'],
    correct: 0,
    fact: 'werk:sixtinische-kapelle',
  },
  {
    id: 'b0016',
    cat: 'allgemeinwissen',
    diff: 'leicht',
    text: 'Wer schrieb „Der alte Mann und das Meer“?',
    options: ['John Steinbeck', 'Francis Scott Fitzgerald', 'Ernest Hemingway', 'William Faulkner'],
    correct: 2,
    fact: 'werk:alter-mann-und-das-meer',
  },
  {
    id: 'b0017',
    cat: 'allgemeinwissen',
    diff: 'leicht',
    text: 'Wie viele Ringe zeigt das olympische Symbol?',
    options: ['4', '6', '7', '5'],
    correct: 3,
    fact: 'sport:olympische-ringe',
  },
  {
    id: 'b0018',
    cat: 'allgemeinwissen',
    diff: 'leicht',
    text: 'Wer betrat 1969 als erster Mensch den Mond?',
    options: ['Buzz Aldrin', 'Neil Armstrong', 'Juri Gagarin', 'Michael Collins'],
    correct: 1,
    fact: 'person:erster-mensch-mond',
  },
  {
    id: 'b0019',
    cat: 'allgemeinwissen',
    diff: 'leicht',
    text: 'In welchem Land fanden die antiken Olympischen Spiele statt?',
    options: ['Italien', 'Ägypten', 'Griechenland', 'Türkei'],
    correct: 2,
    fact: 'sport:antike-olympia-land',
  },
  {
    id: 'b0020',
    cat: 'allgemeinwissen',
    diff: 'leicht',
    text: 'Wer schrieb den Roman „Die Blechtrommel“?',
    options: ['Günter Grass', 'Heinrich Böll', 'Siegfried Lenz', 'Martin Walser'],
    correct: 0,
    fact: 'werk:blechtrommel',
  },
  {
    id: 'b0021',
    cat: 'allgemeinwissen',
    diff: 'leicht',
    text: 'Welche Band veröffentlichte das Album „Abbey Road“?',
    options: ['The Beatles', 'The Rolling Stones', 'Pink Floyd', 'The Who'],
    correct: 0,
    fact: 'werk:abbey-road',
  },
  {
    id: 'b0022',
    cat: 'allgemeinwissen',
    diff: 'leicht',
    text: 'Wie viele Zwerge leben im Märchen mit Schneewittchen?',
    options: ['5', '6', '7', '8'],
    correct: 2,
    fact: 'maerchen:schneewittchen-zwerge',
  },
  {
    id: 'b0023',
    cat: 'allgemeinwissen',
    diff: 'leicht',
    text: 'Wer führte Regie bei dem Film „Der weiße Hai“ von 1975?',
    options: ['George Lucas', 'Francis Ford Coppola', 'Martin Scorsese', 'Steven Spielberg'],
    correct: 3,
    fact: 'film:der-weisse-hai',
  },
  {
    id: 'b0024',
    cat: 'allgemeinwissen',
    diff: 'leicht',
    text: 'Wie viele Felder hat ein Schachbrett?',
    options: ['36', '64', '81', '100'],
    correct: 1,
    fact: 'spiel:schachbrett-felder',
  },

  // ---------------------------------------------------------------------------
  // ALLGEMEINWISSEN — mittel
  // ---------------------------------------------------------------------------
  {
    id: 'b0025',
    cat: 'allgemeinwissen',
    diff: 'mittel',
    text: 'In welchem Jahr begann der Erste Weltkrieg?',
    options: ['1912', '1913', '1914', '1915'],
    correct: 2,
    fact: 'jahr:erster-weltkrieg-beginn',
  },
  {
    id: 'b0026',
    cat: 'allgemeinwissen',
    diff: 'mittel',
    text: 'Wer war der erste Bundeskanzler der Bundesrepublik Deutschland?',
    options: ['Konrad Adenauer', 'Ludwig Erhard', 'Willy Brandt', 'Kurt Georg Kiesinger'],
    correct: 0,
    fact: 'person:erster-bundeskanzler',
  },
  {
    id: 'b0027',
    cat: 'allgemeinwissen',
    diff: 'mittel',
    text: 'Wer komponierte den Opernzyklus „Der Ring des Nibelungen“?',
    options: ['Richard Strauss', 'Giuseppe Verdi', 'Gustav Mahler', 'Richard Wagner'],
    correct: 3,
    fact: 'werk:ring-des-nibelungen',
  },
  {
    id: 'b0028',
    cat: 'allgemeinwissen',
    diff: 'mittel',
    text: 'In welchem Jahr stürmten Aufständische die Bastille in Paris?',
    options: ['1776', '1789', '1799', '1812'],
    correct: 1,
    fact: 'jahr:sturm-auf-bastille',
  },
  {
    id: 'b0029',
    cat: 'allgemeinwissen',
    diff: 'mittel',
    text: 'Wer malte das Gemälde „Sternennacht“?',
    options: ['Vincent van Gogh', 'Paul Cézanne', 'Claude Monet', 'Paul Gauguin'],
    correct: 0,
    fact: 'werk:sternennacht',
  },
  {
    id: 'b0030',
    cat: 'allgemeinwissen',
    diff: 'mittel',
    text: 'Wer wurde 44 v. Chr. an den Iden des März ermordet?',
    options: ['Augustus', 'Marcus Antonius', 'Julius Caesar', 'Nero'],
    correct: 2,
    fact: 'person:iden-des-maerz',
  },
  {
    id: 'b0031',
    cat: 'allgemeinwissen',
    diff: 'mittel',
    text: 'Wer schrieb den Roman „1984“?',
    options: ['Aldous Huxley', 'George Orwell', 'Ray Bradbury', 'Herbert George Wells'],
    correct: 1,
    fact: 'werk:1984',
  },
  {
    id: 'b0032',
    cat: 'allgemeinwissen',
    diff: 'mittel',
    text: 'Welches Instrument spielte Louis Armstrong?',
    options: ['Saxofon', 'Posaune', 'Klarinette', 'Trompete'],
    correct: 3,
    fact: 'musik:louis-armstrong-instrument',
  },
  {
    id: 'b0033',
    cat: 'allgemeinwissen',
    diff: 'mittel',
    text: 'Welcher Kapitän jagt in „Moby-Dick“ den weißen Wal?',
    options: ['Nemo', 'Ismael', 'Starbuck', 'Ahab'],
    correct: 3,
    fact: 'literatur:moby-dick-kapitaen',
  },
  {
    id: 'b0034',
    cat: 'allgemeinwissen',
    diff: 'mittel',
    text: 'In welchem Jahr endete der Zweite Weltkrieg in Europa?',
    options: ['1944', '1945', '1946', '1947'],
    correct: 1,
    fact: 'jahr:kriegsende-europa',
  },
  {
    id: 'b0035',
    cat: 'allgemeinwissen',
    diff: 'mittel',
    text: 'Wer komponierte die Neunte Sinfonie mit der „Ode an die Freude“?',
    options: ['Ludwig van Beethoven', 'Wolfgang Amadeus Mozart', 'Franz Schubert', 'Johannes Brahms'],
    correct: 0,
    fact: 'werk:neunte-sinfonie',
  },
  {
    id: 'b0036',
    cat: 'allgemeinwissen',
    diff: 'mittel',
    text: 'In welchem Jahr wurde Karl der Große zum Kaiser gekrönt?',
    options: ['768', '795', '800', '814'],
    correct: 2,
    fact: 'jahr:kaiserkroenung-karl',
  },
  {
    id: 'b0037',
    cat: 'allgemeinwissen',
    diff: 'mittel',
    text: 'Wer entwickelte in Europa den Buchdruck mit beweglichen Lettern?',
    options: ['William Caxton', 'Johannes Gutenberg', 'Aldus Manutius', 'Anton Koberger'],
    correct: 1,
    fact: 'person:buchdruck-europa',
  },
  {
    id: 'b0038',
    cat: 'allgemeinwissen',
    diff: 'mittel',
    text: 'Wer begründete zusammen mit Georges Braque den Kubismus?',
    options: ['Henri Matisse', 'Salvador Dalí', 'Wassily Kandinsky', 'Pablo Picasso'],
    correct: 3,
    fact: 'kunst:kubismus-mitbegruender',
  },
  {
    id: 'b0039',
    cat: 'allgemeinwissen',
    diff: 'mittel',
    text: 'Wem wird das Epos „Odyssee“ zugeschrieben?',
    options: ['Homer', 'Vergil', 'Sophokles', 'Herodot'],
    correct: 0,
    fact: 'werk:odyssee',
  },
  {
    id: 'b0040',
    cat: 'allgemeinwissen',
    diff: 'mittel',
    text: 'Wie heißt der Hammer des Gottes Thor in der nordischen Mythologie?',
    options: ['Gungnir', 'Gram', 'Mjölnir', 'Draupnir'],
    correct: 2,
    fact: 'mythologie:thors-hammer',
  },
  {
    id: 'b0041',
    cat: 'allgemeinwissen',
    diff: 'mittel',
    text: 'Wer führte Regie bei dem Film „Pulp Fiction“?',
    options: ['Martin Scorsese', 'David Lynch', 'Oliver Stone', 'Quentin Tarantino'],
    correct: 3,
    fact: 'film:pulp-fiction',
  },
  {
    id: 'b0042',
    cat: 'allgemeinwissen',
    diff: 'mittel',
    text: 'Wer schrieb den Roman „Der Steppenwolf“?',
    options: ['Thomas Mann', 'Hermann Hesse', 'Stefan Zweig', 'Alfred Döblin'],
    correct: 1,
    fact: 'werk:steppenwolf',
  },
  {
    id: 'b0043',
    cat: 'allgemeinwissen',
    diff: 'mittel',
    text: 'Welches Instrument machte Jimi Hendrix berühmt?',
    options: ['Schlagzeug', 'Klavier', 'Gitarre', 'Kontrabass'],
    correct: 2,
    fact: 'musik:jimi-hendrix-instrument',
  },
  {
    id: 'b0044',
    cat: 'allgemeinwissen',
    diff: 'mittel',
    text: 'Wie lang ist die offizielle Marathondistanz?',
    options: ['42,195 km', '40,000 km', '45,500 km', '21,097 km'],
    correct: 0,
    fact: 'sport:marathon-distanz',
  },
  {
    id: 'b0045',
    cat: 'allgemeinwissen',
    diff: 'mittel',
    text: 'Welches Land gewann die Fußball-Weltmeisterschaft 1954?',
    options: ['Deutschland', 'Ungarn', 'Brasilien', 'Italien'],
    correct: 0,
    fact: 'sport:wm-1954-sieger',
  },

  // ---------------------------------------------------------------------------
  // ALLGEMEINWISSEN — schwer
  // ---------------------------------------------------------------------------
  {
    id: 'b0046',
    cat: 'allgemeinwissen',
    diff: 'schwer',
    text: 'Wer schrieb „Auf der Suche nach der verlorenen Zeit“?',
    options: ['André Gide', 'Gustave Flaubert', 'Marcel Proust', 'Albert Camus'],
    correct: 2,
    fact: 'werk:suche-verlorene-zeit',
  },
  {
    id: 'b0047',
    cat: 'allgemeinwissen',
    diff: 'schwer',
    text: 'In welchem Jahr wurde der Westfälische Friede geschlossen?',
    options: ['1618', '1635', '1659', '1648'],
    correct: 3,
    fact: 'jahr:westfaelischer-friede',
  },
  {
    id: 'b0048',
    cat: 'allgemeinwissen',
    diff: 'schwer',
    text: 'Wer komponierte die Oper „Wozzeck“?',
    options: ['Arnold Schönberg', 'Alban Berg', 'Anton Webern', 'Paul Hindemith'],
    correct: 1,
    fact: 'werk:wozzeck',
  },
  {
    id: 'b0049',
    cat: 'allgemeinwissen',
    diff: 'schwer',
    text: 'Wer überquerte 218 v. Chr. mit Kriegselefanten die Alpen?',
    options: ['Scipio', 'Pyrrhos', 'Hannibal', 'Vercingetorix'],
    correct: 2,
    fact: 'person:alpenueberquerung-elefanten',
  },
  {
    id: 'b0050',
    cat: 'allgemeinwissen',
    diff: 'schwer',
    text: 'Wer schrieb das Theaterstück „Warten auf Godot“?',
    options: ['Samuel Beckett', 'Eugène Ionesco', 'Jean-Paul Sartre', 'Harold Pinter'],
    correct: 0,
    fact: 'werk:warten-auf-godot',
  },
  {
    id: 'b0051',
    cat: 'allgemeinwissen',
    diff: 'schwer',
    text: 'In welchem Jahr wurde die Magna Carta besiegelt?',
    options: ['1066', '1189', '1265', '1215'],
    correct: 3,
    fact: 'jahr:magna-carta',
  },
  {
    id: 'b0052',
    cat: 'allgemeinwissen',
    diff: 'schwer',
    text: 'Wer malte das Triptychon „Der Garten der Lüste“?',
    options: ['Pieter Bruegel der Ältere', 'Hieronymus Bosch', 'Jan van Eyck', 'Matthias Grünewald'],
    correct: 1,
    fact: 'werk:garten-der-lueste',
  },
  {
    id: 'b0053',
    cat: 'allgemeinwissen',
    diff: 'schwer',
    text: 'Welcher Philosoph war der Lehrer Alexanders des Großen?',
    options: ['Aristoteles', 'Platon', 'Sokrates', 'Epikur'],
    correct: 0,
    fact: 'person:lehrer-alexanders',
  },
  {
    id: 'b0054',
    cat: 'allgemeinwissen',
    diff: 'schwer',
    text: 'Wer schrieb den Gedichtband „Die Blumen des Bösen“?',
    options: ['Arthur Rimbaud', 'Paul Verlaine', 'Charles Baudelaire', 'Stéphane Mallarmé'],
    correct: 2,
    fact: 'werk:blumen-des-boesen',
  },
  {
    id: 'b0055',
    cat: 'allgemeinwissen',
    diff: 'schwer',
    text: 'In welchem Jahr eroberten die Osmanen Konstantinopel?',
    options: ['1389', '1453', '1492', '1517'],
    correct: 1,
    fact: 'jahr:eroberung-konstantinopel',
  },
  {
    id: 'b0056',
    cat: 'allgemeinwissen',
    diff: 'schwer',
    text: 'Wer gilt als der erste römische Kaiser?',
    options: ['Julius Caesar', 'Tiberius', 'Nero', 'Augustus'],
    correct: 3,
    fact: 'person:erster-roemischer-kaiser',
  },
  {
    id: 'b0057',
    cat: 'allgemeinwissen',
    diff: 'schwer',
    text: 'Wer entwarf das Guggenheim-Museum in New York?',
    options: ['Le Corbusier', 'Mies van der Rohe', 'Walter Gropius', 'Frank Lloyd Wright'],
    correct: 3,
    fact: 'bauwerk:guggenheim-new-york',
  },
  {
    id: 'b0058',
    cat: 'allgemeinwissen',
    diff: 'schwer',
    text: 'Wer verfasste die Schrift „Der Fürst“?',
    options: ['Thomas Morus', 'Niccolò Machiavelli', 'Erasmus von Rotterdam', 'Baldassare Castiglione'],
    correct: 1,
    fact: 'werk:der-fuerst',
  },
  {
    id: 'b0059',
    cat: 'allgemeinwissen',
    diff: 'schwer',
    text: 'Welche Dynastie regierte China von 1368 bis 1644?',
    options: ['Ming', 'Qing', 'Song', 'Tang'],
    correct: 0,
    fact: 'geschichte:ming-dynastie',
  },
  {
    id: 'b0060',
    cat: 'allgemeinwissen',
    diff: 'schwer',
    text: 'Wer gründete 1919 das Bauhaus in Weimar?',
    options: ['Hannes Meyer', 'Bruno Taut', 'Walter Gropius', 'Mies van der Rohe'],
    correct: 2,
    fact: 'kunst:bauhaus-gruender',
  },

  // ---------------------------------------------------------------------------
  // WISSENSCHAFT — leicht
  // ---------------------------------------------------------------------------
  {
    id: 'b0061',
    cat: 'wissenschaft',
    diff: 'leicht',
    text: 'Welches chemische Symbol steht für Gold?',
    options: ['Ag', 'Au', 'Gd', 'Go'],
    correct: 1,
    fact: 'element:symbol-gold',
  },
  {
    id: 'b0062',
    cat: 'wissenschaft',
    diff: 'leicht',
    text: 'Welches Gas benötigt der Mensch zum Atmen?',
    options: ['Stickstoff', 'Kohlendioxid', 'Helium', 'Sauerstoff'],
    correct: 3,
    fact: 'biologie:atemgas',
  },
  {
    id: 'b0063',
    cat: 'wissenschaft',
    diff: 'leicht',
    text: 'Wie viele Beine hat eine Spinne?',
    options: ['8', '6', '4', '10'],
    correct: 0,
    fact: 'biologie:spinne-beine',
  },
  {
    id: 'b0064',
    cat: 'wissenschaft',
    diff: 'leicht',
    text: 'Wie lautet die chemische Formel von Wasser?',
    options: ['CO2', 'O2', 'H2O', 'H2O2'],
    correct: 2,
    fact: 'chemie:formel-wasser',
  },
  {
    id: 'b0065',
    cat: 'wissenschaft',
    diff: 'leicht',
    text: 'Welches Organ pumpt das Blut durch den Körper?',
    options: ['Lunge', 'Leber', 'Niere', 'Herz'],
    correct: 3,
    fact: 'medizin:blutpumpe',
  },
  {
    id: 'b0066',
    cat: 'wissenschaft',
    diff: 'leicht',
    text: 'Bei wie viel Grad Celsius gefriert Wasser auf Meereshöhe?',
    options: ['minus 10 Grad', '0 Grad', '10 Grad', '32 Grad'],
    correct: 1,
    fact: 'physik:gefrierpunkt-wasser',
  },
  {
    id: 'b0067',
    cat: 'wissenschaft',
    diff: 'leicht',
    text: 'Welcher Planet kreist der Sonne am nächsten?',
    options: ['Venus', 'Erde', 'Merkur', 'Mars'],
    correct: 2,
    fact: 'astronomie:sonnennaechster-planet',
  },
  {
    id: 'b0068',
    cat: 'wissenschaft',
    diff: 'leicht',
    text: 'Welches Element hat das chemische Symbol O?',
    options: ['Sauerstoff', 'Osmium', 'Gold', 'Stickstoff'],
    correct: 0,
    fact: 'element:symbol-o',
  },
  {
    id: 'b0069',
    cat: 'wissenschaft',
    diff: 'leicht',
    text: 'Wie viele Zähne hat ein Erwachsener mit allen Weisheitszähnen?',
    options: ['32', '28', '30', '36'],
    correct: 0,
    fact: 'medizin:zahnzahl-erwachsener',
  },
  {
    id: 'b0070',
    cat: 'wissenschaft',
    diff: 'leicht',
    text: 'Welches Messgerät zeigt den Luftdruck an?',
    options: ['Hygrometer', 'Anemometer', 'Barometer', 'Seismograf'],
    correct: 2,
    fact: 'technik:luftdruck-messgeraet',
  },
  {
    id: 'b0071',
    cat: 'wissenschaft',
    diff: 'leicht',
    text: 'Wie viele Chromosomenpaare besitzt eine menschliche Körperzelle?',
    options: ['21', '22', '24', '23'],
    correct: 3,
    fact: 'biologie:chromosomenpaare-mensch',
  },
  {
    id: 'b0072',
    cat: 'wissenschaft',
    diff: 'leicht',
    text: 'Welches dieser Meerestiere ist ein Säugetier?',
    options: ['Hai', 'Delfin', 'Thunfisch', 'Rochen'],
    correct: 1,
    fact: 'biologie:delfin-saeugetier',
  },
  {
    id: 'b0073',
    cat: 'wissenschaft',
    diff: 'leicht',
    text: 'Aus welchem Element besteht ein Diamant?',
    options: ['Silizium', 'Bor', 'Kohlenstoff', 'Schwefel'],
    correct: 2,
    fact: 'chemie:diamant-bestandteil',
  },
  {
    id: 'b0074',
    cat: 'wissenschaft',
    diff: 'leicht',
    text: 'Welche Kraft hält die Planeten auf ihrer Bahn um die Sonne?',
    options: ['Gravitation', 'Magnetismus', 'Reibung', 'Kernkraft'],
    correct: 0,
    fact: 'physik:planetenbahn-kraft',
  },
  {
    id: 'b0075',
    cat: 'wissenschaft',
    diff: 'leicht',
    text: 'Wie heißt der Vorgang, mit dem Pflanzen Licht in Zucker umwandeln?',
    options: ['Zellatmung', 'Osmose', 'Gärung', 'Photosynthese'],
    correct: 3,
    fact: 'biologie:photosynthese',
  },
  {
    id: 'b0076',
    cat: 'wissenschaft',
    diff: 'leicht',
    text: 'Wie viele Flächen hat ein Würfel?',
    options: ['4', '6', '8', '12'],
    correct: 1,
    fact: 'mathematik:wuerfel-flaechen',
  },
  {
    id: 'b0077',
    cat: 'wissenschaft',
    diff: 'leicht',
    text: 'Wie groß ist die Quadratwurzel aus 144?',
    options: ['12', '11', '13', '14'],
    correct: 0,
    fact: 'mathematik:wurzel-144',
  },
  {
    id: 'b0078',
    cat: 'wissenschaft',
    diff: 'leicht',
    text: 'Welches Metall ist bei Raumtemperatur flüssig?',
    options: ['Blei', 'Zinn', 'Quecksilber', 'Zink'],
    correct: 2,
    fact: 'chemie:fluessiges-metall',
  },
  {
    id: 'b0079',
    cat: 'wissenschaft',
    diff: 'leicht',
    text: 'Wie viel Grad misst ein rechter Winkel?',
    options: ['45', '90', '120', '180'],
    correct: 1,
    fact: 'mathematik:rechter-winkel',
  },
  {
    id: 'b0080',
    cat: 'wissenschaft',
    diff: 'leicht',
    text: 'Welches Organ produziert das Hormon Insulin?',
    options: ['Leber', 'Milz', 'Schilddrüse', 'Bauchspeicheldrüse'],
    correct: 3,
    fact: 'medizin:insulinproduktion',
  },
  {
    id: 'b0081',
    cat: 'wissenschaft',
    diff: 'leicht',
    text: 'Welcher Planet trägt den Beinamen „Roter Planet“?',
    options: ['Venus', 'Jupiter', 'Merkur', 'Mars'],
    correct: 3,
    fact: 'astronomie:roter-planet',
  },
  {
    id: 'b0082',
    cat: 'wissenschaft',
    diff: 'leicht',
    text: 'Aus wie vielen Vorhöfen und Kammern besteht das menschliche Herz?',
    options: ['2', '4', '6', '8'],
    correct: 1,
    fact: 'medizin:herz-hohlraeume',
  },
  {
    id: 'b0083',
    cat: 'wissenschaft',
    diff: 'leicht',
    text: 'Welches Gas lässt Mineralwasser sprudeln?',
    options: ['Kohlendioxid', 'Sauerstoff', 'Stickstoff', 'Wasserstoff'],
    correct: 0,
    fact: 'chemie:kohlensaeure-gas',
  },
  {
    id: 'b0084',
    cat: 'wissenschaft',
    diff: 'leicht',
    text: 'Bei wie viel Grad Celsius siedet Wasser auf Meereshöhe?',
    options: ['80', '90', '100', '120'],
    correct: 2,
    fact: 'physik:siedepunkt-wasser',
  },

  // ---------------------------------------------------------------------------
  // WISSENSCHAFT — mittel
  // ---------------------------------------------------------------------------
  {
    id: 'b0085',
    cat: 'wissenschaft',
    diff: 'mittel',
    text: 'Welches Element hat die Ordnungszahl 1?',
    options: ['Helium', 'Wasserstoff', 'Kohlenstoff', 'Sauerstoff'],
    correct: 1,
    fact: 'element:ordnungszahl-1',
  },
  {
    id: 'b0086',
    cat: 'wissenschaft',
    diff: 'mittel',
    text: 'Wer formulierte die spezielle Relativitätstheorie?',
    options: ['Niels Bohr', 'Max Planck', 'Werner Heisenberg', 'Albert Einstein'],
    correct: 3,
    fact: 'physik:relativitaetstheorie-urheber',
  },
  {
    id: 'b0087',
    cat: 'wissenschaft',
    diff: 'mittel',
    text: 'Welches Gas hat den größten Anteil an der Erdatmosphäre?',
    options: ['Stickstoff', 'Sauerstoff', 'Kohlendioxid', 'Argon'],
    correct: 0,
    fact: 'chemie:hauptgas-atmosphaere',
  },
  {
    id: 'b0088',
    cat: 'wissenschaft',
    diff: 'mittel',
    text: 'Wie heißt die Einheit der elektrischen Stromstärke?',
    options: ['Volt', 'Ohm', 'Ampere', 'Watt'],
    correct: 2,
    fact: 'physik:einheit-stromstaerke',
  },
  {
    id: 'b0089',
    cat: 'wissenschaft',
    diff: 'mittel',
    text: 'Welcher Planet ist für sein auffälliges Ringsystem bekannt?',
    options: ['Mars', 'Merkur', 'Venus', 'Saturn'],
    correct: 3,
    fact: 'astronomie:ringplanet',
  },
  {
    id: 'b0090',
    cat: 'wissenschaft',
    diff: 'mittel',
    text: 'Wer veröffentlichte 1869 das Periodensystem der Elemente?',
    options: ['Antoine Lavoisier', 'Dmitri Mendelejew', 'John Dalton', 'Robert Bunsen'],
    correct: 1,
    fact: 'chemie:periodensystem-urheber',
  },
  {
    id: 'b0091',
    cat: 'wissenschaft',
    diff: 'mittel',
    text: 'Welche Blutzellen transportieren den Sauerstoff?',
    options: ['Weiße Blutkörperchen', 'Blutplättchen', 'Rote Blutkörperchen', 'Lymphozyten'],
    correct: 2,
    fact: 'medizin:sauerstofftransport-blut',
  },
  {
    id: 'b0092',
    cat: 'wissenschaft',
    diff: 'mittel',
    text: 'Wie viele Knochen hat das Skelett eines Erwachsenen?',
    options: ['206', '186', '226', '246'],
    correct: 0,
    fact: 'medizin:knochenzahl-erwachsener',
  },
  {
    id: 'b0093',
    cat: 'wissenschaft',
    diff: 'mittel',
    text: 'Welches Element hat das chemische Symbol Fe?',
    options: ['Eisen', 'Blei', 'Kupfer', 'Zink'],
    correct: 0,
    fact: 'element:symbol-fe',
  },
  {
    id: 'b0094',
    cat: 'wissenschaft',
    diff: 'mittel',
    text: 'Wer entdeckte 1928 das Penicillin?',
    options: ['Louis Pasteur', 'Robert Koch', 'Alexander Fleming', 'Paul Ehrlich'],
    correct: 2,
    fact: 'medizin:penicillin-entdecker',
  },
  {
    id: 'b0095',
    cat: 'wissenschaft',
    diff: 'mittel',
    text: 'Wie heißt die Einheit der Frequenz?',
    options: ['Newton', 'Joule', 'Pascal', 'Hertz'],
    correct: 3,
    fact: 'physik:einheit-frequenz',
  },
  {
    id: 'b0096',
    cat: 'wissenschaft',
    diff: 'mittel',
    text: 'Wie heißt die Wissenschaft von den Erdbeben?',
    options: ['Vulkanologie', 'Seismologie', 'Geodäsie', 'Meteorologie'],
    correct: 1,
    fact: 'wissenschaft:erdbebenlehre',
  },
  {
    id: 'b0097',
    cat: 'wissenschaft',
    diff: 'mittel',
    text: 'Welches Teilchen im Atomkern trägt keine elektrische Ladung?',
    options: ['Proton', 'Elektron', 'Neutron', 'Positron'],
    correct: 2,
    fact: 'physik:neutrales-kernteilchen',
  },
  {
    id: 'b0098',
    cat: 'wissenschaft',
    diff: 'mittel',
    text: 'Wie lautet der Satz des Pythagoras im rechtwinkligen Dreieck?',
    options: ['a² + b² = c²', 'a + b = c', 'a² − b² = c²', 'a · b = c²'],
    correct: 0,
    fact: 'mathematik:satz-des-pythagoras',
  },
  {
    id: 'b0099',
    cat: 'wissenschaft',
    diff: 'mittel',
    text: 'Welches Vitamin bildet die Haut unter Sonnenlicht?',
    options: ['Vitamin A', 'Vitamin C', 'Vitamin B12', 'Vitamin D'],
    correct: 3,
    fact: 'medizin:sonnenlicht-vitamin',
  },
  {
    id: 'b0100',
    cat: 'wissenschaft',
    diff: 'mittel',
    text: 'Wer schrieb das Werk „Über die Entstehung der Arten“?',
    options: ['Jean-Baptiste Lamarck', 'Charles Darwin', 'Gregor Mendel', 'Carl von Linné'],
    correct: 1,
    fact: 'biologie:entstehung-der-arten',
  },
  {
    id: 'b0101',
    cat: 'wissenschaft',
    diff: 'mittel',
    text: 'Wie heißt die Teilung gewöhnlicher Körperzellen?',
    options: ['Mitose', 'Meiose', 'Mutation', 'Osmose'],
    correct: 0,
    fact: 'biologie:zellteilung-koerperzellen',
  },
  {
    id: 'b0102',
    cat: 'wissenschaft',
    diff: 'mittel',
    text: 'Welches Metall leitet elektrischen Strom am besten?',
    options: ['Kupfer', 'Gold', 'Silber', 'Aluminium'],
    correct: 2,
    fact: 'physik:bester-stromleiter',
  },
  {
    id: 'b0103',
    cat: 'wissenschaft',
    diff: 'mittel',
    text: 'Welche Galaxie trägt die Katalogbezeichnung M31?',
    options: ['Dreiecksgalaxie', 'Andromedagalaxie', 'Sombrerogalaxie', 'Strudelgalaxie'],
    correct: 1,
    fact: 'astronomie:m31',
  },
  {
    id: 'b0104',
    cat: 'wissenschaft',
    diff: 'mittel',
    text: 'Wie groß ist die Winkelsumme in einem ebenen Dreieck?',
    options: ['90 Grad', '270 Grad', '360 Grad', '180 Grad'],
    correct: 3,
    fact: 'mathematik:winkelsumme-dreieck',
  },
  {
    id: 'b0105',
    cat: 'wissenschaft',
    diff: 'mittel',
    text: 'Welches Element kommt im Universum am häufigsten vor?',
    options: ['Helium', 'Sauerstoff', 'Kohlenstoff', 'Wasserstoff'],
    correct: 3,
    fact: 'astronomie:haeufigstes-element-universum',
  },

  // ---------------------------------------------------------------------------
  // WISSENSCHAFT — schwer
  // ---------------------------------------------------------------------------
  {
    id: 'b0106',
    cat: 'wissenschaft',
    diff: 'schwer',
    text: 'Wer stellte die drei Gesetze der Planetenbewegung auf?',
    options: ['Nikolaus Kopernikus', 'Johannes Kepler', 'Galileo Galilei', 'Tycho Brahe'],
    correct: 1,
    fact: 'astronomie:planetengesetze-urheber',
  },
  {
    id: 'b0107',
    cat: 'wissenschaft',
    diff: 'schwer',
    text: 'Welches Element hat die Ordnungszahl 79?',
    options: ['Gold', 'Silber', 'Platin', 'Quecksilber'],
    correct: 0,
    fact: 'element:ordnungszahl-79',
  },
  {
    id: 'b0108',
    cat: 'wissenschaft',
    diff: 'schwer',
    text: 'Wie heißt die SI-Einheit der radioaktiven Aktivität?',
    options: ['Sievert', 'Gray', 'Becquerel', 'Curie'],
    correct: 2,
    fact: 'physik:einheit-aktivitaet',
  },
  {
    id: 'b0109',
    cat: 'wissenschaft',
    diff: 'schwer',
    text: 'Welches Enzym im Speichel spaltet Stärke?',
    options: ['Pepsin', 'Amylase', 'Lipase', 'Trypsin'],
    correct: 1,
    fact: 'biologie:speichelenzym',
  },
  {
    id: 'b0110',
    cat: 'wissenschaft',
    diff: 'schwer',
    text: 'Welche räumliche Struktur bildet ein DNA-Molekül?',
    options: ['Alpha-Helix', 'Beta-Faltblatt', 'Tripelhelix', 'Doppelhelix'],
    correct: 3,
    fact: 'biologie:dna-struktur',
  },
  {
    id: 'b0111',
    cat: 'wissenschaft',
    diff: 'schwer',
    text: 'Wer formulierte die Unschärferelation der Quantenmechanik?',
    options: ['Werner Heisenberg', 'Erwin Schrödinger', 'Max Born', 'Wolfgang Pauli'],
    correct: 0,
    fact: 'physik:unschaerferelation',
  },
  {
    id: 'b0112',
    cat: 'wissenschaft',
    diff: 'schwer',
    text: 'Welches Element hat das chemische Symbol W?',
    options: ['Wasserstoff', 'Vanadium', 'Wolfram', 'Wismut'],
    correct: 2,
    fact: 'element:symbol-w',
  },
  {
    id: 'b0113',
    cat: 'wissenschaft',
    diff: 'schwer',
    text: 'Wie schnell ist Licht im Vakuum ungefähr?',
    options: ['30 000 km/s', '150 000 km/s', '3 000 000 km/s', '300 000 km/s'],
    correct: 3,
    fact: 'physik:lichtgeschwindigkeit',
  },
  {
    id: 'b0114',
    cat: 'wissenschaft',
    diff: 'schwer',
    text: 'Wie heißt der Übergang von fest direkt zu gasförmig?',
    options: ['Kondensation', 'Sublimation', 'Resublimation', 'Verdampfung'],
    correct: 1,
    fact: 'chemie:fest-zu-gas',
  },
  {
    id: 'b0115',
    cat: 'wissenschaft',
    diff: 'schwer',
    text: 'Wer bewies die Unvollständigkeitssätze der Mathematik?',
    options: ['David Hilbert', 'Alan Turing', 'Kurt Gödel', 'Bertrand Russell'],
    correct: 2,
    fact: 'mathematik:unvollstaendigkeitssaetze',
  },
  {
    id: 'b0116',
    cat: 'wissenschaft',
    diff: 'schwer',
    text: 'Welches Gesetz besagt: Kraft ist Masse mal Beschleunigung?',
    options: ['Zweites Newtonsches Gesetz', 'Hookesches Gesetz', 'Ohmsches Gesetz', 'Gesetz von Boyle'],
    correct: 0,
    fact: 'physik:kraft-masse-beschleunigung',
  },
  {
    id: 'b0117',
    cat: 'wissenschaft',
    diff: 'schwer',
    text: 'Wie heißt die Verschmelzung leichter Atomkerne zu schwereren?',
    options: ['Kernfusion', 'Kernspaltung', 'Radioaktiver Zerfall', 'Ionisation'],
    correct: 0,
    fact: 'physik:kernverschmelzung',
  },
  {
    id: 'b0118',
    cat: 'wissenschaft',
    diff: 'schwer',
    text: 'Wer entdeckte 1895 die nach ihm benannten Strahlen?',
    options: ['Henri Becquerel', 'Marie Curie', 'Wilhelm Conrad Röntgen', 'Ernest Rutherford'],
    correct: 2,
    fact: 'physik:roentgenstrahlen-entdecker',
  },
  {
    id: 'b0119',
    cat: 'wissenschaft',
    diff: 'schwer',
    text: 'Aus wie vielen Basen besteht ein Codon im genetischen Code?',
    options: ['2', '4', '6', '3'],
    correct: 3,
    fact: 'biologie:codon-laenge',
  },
  {
    id: 'b0120',
    cat: 'wissenschaft',
    diff: 'schwer',
    text: 'Wie heißt der kleinste Knochen im menschlichen Körper?',
    options: ['Amboss', 'Steigbügel', 'Hammer', 'Speiche'],
    correct: 1,
    fact: 'medizin:kleinster-knochen',
  },

  // ---------------------------------------------------------------------------
  // GEOGRAFIE — leicht
  // ---------------------------------------------------------------------------
  {
    id: 'b0121',
    cat: 'geografie',
    diff: 'leicht',
    text: 'Wie heißt die Hauptstadt von Frankreich?',
    options: ['Lyon', 'Marseille', 'Paris', 'Bordeaux'],
    correct: 2,
    fact: 'hauptstadt:frankreich',
  },
  {
    id: 'b0122',
    cat: 'geografie',
    diff: 'leicht',
    text: 'Wie heißt die Hauptstadt von Italien?',
    options: ['Rom', 'Mailand', 'Neapel', 'Turin'],
    correct: 0,
    fact: 'hauptstadt:italien',
  },
  {
    id: 'b0123',
    cat: 'geografie',
    diff: 'leicht',
    text: 'Wie heißt die Hauptstadt von Japan?',
    options: ['Osaka', 'Kyoto', 'Nagoya', 'Tokio'],
    correct: 3,
    fact: 'hauptstadt:japan',
  },
  {
    id: 'b0124',
    cat: 'geografie',
    diff: 'leicht',
    text: 'Wie heißt die Hauptstadt von Spanien?',
    options: ['Barcelona', 'Madrid', 'Sevilla', 'Valencia'],
    correct: 1,
    fact: 'hauptstadt:spanien',
  },
  {
    id: 'b0125',
    cat: 'geografie',
    diff: 'leicht',
    text: 'Wie heißt die Hauptstadt von Australien?',
    options: ['Canberra', 'Sydney', 'Melbourne', 'Brisbane'],
    correct: 0,
    fact: 'hauptstadt:australien',
  },
  {
    id: 'b0126',
    cat: 'geografie',
    diff: 'leicht',
    text: 'Welcher Fluss fließt durch Wien?',
    options: ['Rhein', 'Elbe', 'Donau', 'Inn'],
    correct: 2,
    fact: 'fluss:wien',
  },
  {
    id: 'b0127',
    cat: 'geografie',
    diff: 'leicht',
    text: 'Welcher Ozean liegt zwischen Europa und Nordamerika?',
    options: ['Pazifik', 'Atlantik', 'Indischer Ozean', 'Nordpolarmeer'],
    correct: 1,
    fact: 'meer:zwischen-europa-amerika',
  },
  {
    id: 'b0128',
    cat: 'geografie',
    diff: 'leicht',
    text: 'In welchem Land steht der Eiffelturm?',
    options: ['Belgien', 'Italien', 'Schweiz', 'Frankreich'],
    correct: 3,
    fact: 'bauwerk:eiffelturm-land',
  },
  {
    id: 'b0129',
    cat: 'geografie',
    diff: 'leicht',
    text: 'Welches Land hat auf der Karte die Form eines Stiefels?',
    options: ['Griechenland', 'Portugal', 'Kroatien', 'Italien'],
    correct: 3,
    fact: 'land:stiefelform',
  },
  {
    id: 'b0130',
    cat: 'geografie',
    diff: 'leicht',
    text: 'Wie heißt der höchste Berg Deutschlands?',
    options: ['Watzmann', 'Zugspitze', 'Feldberg', 'Brocken'],
    correct: 1,
    fact: 'berg:hoechster-deutschland',
  },
  {
    id: 'b0131',
    cat: 'geografie',
    diff: 'leicht',
    text: 'Wie heißt die Hauptstadt von Deutschland?',
    options: ['Berlin', 'München', 'Hamburg', 'Köln'],
    correct: 0,
    fact: 'hauptstadt:deutschland',
  },
  {
    id: 'b0132',
    cat: 'geografie',
    diff: 'leicht',
    text: 'Welcher Fluss fließt durch Paris?',
    options: ['Loire', 'Rhône', 'Seine', 'Garonne'],
    correct: 2,
    fact: 'fluss:paris',
  },
  {
    id: 'b0133',
    cat: 'geografie',
    diff: 'leicht',
    text: 'Wie heißt die Hauptstadt des Vereinigten Königreichs?',
    options: ['Manchester', 'London', 'Edinburgh', 'Birmingham'],
    correct: 1,
    fact: 'hauptstadt:vereinigtes-koenigreich',
  },
  {
    id: 'b0134',
    cat: 'geografie',
    diff: 'leicht',
    text: 'In welcher Stadt hat die Schweizer Bundesregierung ihren Sitz?',
    options: ['Zürich', 'Genf', 'Basel', 'Bern'],
    correct: 3,
    fact: 'regierungssitz:schweiz',
  },
  {
    id: 'b0135',
    cat: 'geografie',
    diff: 'leicht',
    text: 'Wie heißt die Hauptstadt von Österreich?',
    options: ['Wien', 'Salzburg', 'Graz', 'Linz'],
    correct: 0,
    fact: 'hauptstadt:oesterreich',
  },
  {
    id: 'b0136',
    cat: 'geografie',
    diff: 'leicht',
    text: 'Welche Insel liegt direkt an der Stiefelspitze Italiens?',
    options: ['Korsika', 'Sardinien', 'Sizilien', 'Kreta'],
    correct: 2,
    fact: 'insel:stiefelspitze',
  },
  {
    id: 'b0137',
    cat: 'geografie',
    diff: 'leicht',
    text: 'In welchem Land stehen die Pyramiden von Gizeh?',
    options: ['Sudan', 'Libyen', 'Israel', 'Ägypten'],
    correct: 3,
    fact: 'bauwerk:pyramiden-gizeh-land',
  },
  {
    id: 'b0138',
    cat: 'geografie',
    diff: 'leicht',
    text: 'Welches Gebirge liegt zwischen Spanien und Frankreich?',
    options: ['Alpen', 'Pyrenäen', 'Apennin', 'Karpaten'],
    correct: 1,
    fact: 'gebirge:spanien-frankreich',
  },
  {
    id: 'b0139',
    cat: 'geografie',
    diff: 'leicht',
    text: 'Welcher Ozean der Erde ist der größte?',
    options: ['Atlantik', 'Indischer Ozean', 'Pazifik', 'Nordpolarmeer'],
    correct: 2,
    fact: 'meer:groesster-ozean',
  },
  {
    id: 'b0140',
    cat: 'geografie',
    diff: 'leicht',
    text: 'In welchem Land liegt die Stadt Sydney?',
    options: ['Australien', 'Neuseeland', 'Südafrika', 'Kanada'],
    correct: 0,
    fact: 'stadt:sydney-land',
  },
  {
    id: 'b0141',
    cat: 'geografie',
    diff: 'leicht',
    text: 'Wie heißt die Hauptstadt der USA?',
    options: ['Washington, D.C.', 'New York', 'Los Angeles', 'Chicago'],
    correct: 0,
    fact: 'hauptstadt:usa',
  },
  {
    id: 'b0142',
    cat: 'geografie',
    diff: 'leicht',
    text: 'Auf welchem Kontinent liegt der Südpol?',
    options: ['Europa', 'Asien', 'Antarktika', 'Nordamerika'],
    correct: 2,
    fact: 'kontinent:suedpol',
  },
  {
    id: 'b0143',
    cat: 'geografie',
    diff: 'leicht',
    text: 'Welcher Fluss fließt durch Kairo?',
    options: ['Kongo', 'Sambesi', 'Niger', 'Nil'],
    correct: 3,
    fact: 'fluss:kairo',
  },
  {
    id: 'b0144',
    cat: 'geografie',
    diff: 'leicht',
    text: 'Wie heißt die Hauptstadt von Russland?',
    options: ['Sankt Petersburg', 'Moskau', 'Nowosibirsk', 'Jekaterinburg'],
    correct: 1,
    fact: 'hauptstadt:russland',
  },

  // ---------------------------------------------------------------------------
  // GEOGRAFIE — mittel
  // ---------------------------------------------------------------------------
  {
    id: 'b0145',
    cat: 'geografie',
    diff: 'mittel',
    text: 'Wie heißt die Hauptstadt von Kanada?',
    options: ['Toronto', 'Montreal', 'Ottawa', 'Vancouver'],
    correct: 2,
    fact: 'hauptstadt:kanada',
  },
  {
    id: 'b0146',
    cat: 'geografie',
    diff: 'mittel',
    text: 'Wie heißt die Hauptstadt von Brasilien?',
    options: ['Brasília', 'Rio de Janeiro', 'São Paulo', 'Salvador'],
    correct: 0,
    fact: 'hauptstadt:brasilien',
  },
  {
    id: 'b0147',
    cat: 'geografie',
    diff: 'mittel',
    text: 'Wie heißt die Hauptstadt der Türkei?',
    options: ['Istanbul', 'Izmir', 'Bursa', 'Ankara'],
    correct: 3,
    fact: 'hauptstadt:tuerkei',
  },
  {
    id: 'b0148',
    cat: 'geografie',
    diff: 'mittel',
    text: 'Durch welche dieser deutschen Städte fließt die Elbe?',
    options: ['Köln', 'Dresden', 'München', 'Nürnberg'],
    correct: 1,
    fact: 'fluss:elbe-stadt',
  },
  {
    id: 'b0149',
    cat: 'geografie',
    diff: 'mittel',
    text: 'Welches Gebirge zieht sich an der Westküste Südamerikas entlang?',
    options: ['Anden', 'Rocky Mountains', 'Atlas', 'Ural'],
    correct: 0,
    fact: 'gebirge:suedamerika-westkueste',
  },
  {
    id: 'b0150',
    cat: 'geografie',
    diff: 'mittel',
    text: 'Welcher See hat die größte Fläche in Afrika?',
    options: ['Tanganjikasee', 'Malawisee', 'Victoriasee', 'Tschadsee'],
    correct: 2,
    fact: 'see:groesste-flaeche-afrika',
  },
  {
    id: 'b0151',
    cat: 'geografie',
    diff: 'mittel',
    text: 'Welches Land umschließt die Republik San Marino vollständig?',
    options: ['Frankreich', 'Italien', 'Schweiz', 'Spanien'],
    correct: 1,
    fact: 'land:umgibt-san-marino',
  },
  {
    id: 'b0152',
    cat: 'geografie',
    diff: 'mittel',
    text: 'Welche Meerenge trennt Spanien von Marokko?',
    options: ['Bosporus', 'Ärmelkanal', 'Dardanellen', 'Straße von Gibraltar'],
    correct: 3,
    fact: 'meerenge:spanien-marokko',
  },
  {
    id: 'b0153',
    cat: 'geografie',
    diff: 'mittel',
    text: 'Wie heißt die Hauptstadt von Norwegen?',
    options: ['Bergen', 'Stavanger', 'Trondheim', 'Oslo'],
    correct: 3,
    fact: 'hauptstadt:norwegen',
  },
  {
    id: 'b0154',
    cat: 'geografie',
    diff: 'mittel',
    text: 'Wie heißt die Hauptstadt von Portugal?',
    options: ['Porto', 'Lissabon', 'Coimbra', 'Faro'],
    correct: 1,
    fact: 'hauptstadt:portugal',
  },
  {
    id: 'b0155',
    cat: 'geografie',
    diff: 'mittel',
    text: 'Welcher Kanal verbindet das Mittelmeer mit dem Roten Meer?',
    options: ['Sueskanal', 'Panamakanal', 'Nord-Ostsee-Kanal', 'Kanal von Korinth'],
    correct: 0,
    fact: 'kanal:mittelmeer-rotes-meer',
  },
  {
    id: 'b0156',
    cat: 'geografie',
    diff: 'mittel',
    text: 'Zu welchem Land gehört die Insel Kreta?',
    options: ['Italien', 'Türkei', 'Griechenland', 'Zypern'],
    correct: 2,
    fact: 'insel:kreta-land',
  },
  {
    id: 'b0157',
    cat: 'geografie',
    diff: 'mittel',
    text: 'Welcher Fluss bildet einen Großteil der Grenze USA–Mexiko?',
    options: ['Colorado', 'Rio Grande', 'Mississippi', 'Missouri'],
    correct: 1,
    fact: 'fluss:usa-mexiko-grenze',
  },
  {
    id: 'b0158',
    cat: 'geografie',
    diff: 'mittel',
    text: 'Welche Insel der Erde hat die größte Fläche?',
    options: ['Neuguinea', 'Borneo', 'Madagaskar', 'Grönland'],
    correct: 3,
    fact: 'insel:groesste-welt',
  },
  {
    id: 'b0159',
    cat: 'geografie',
    diff: 'mittel',
    text: 'Welcher Vulkan verschüttete im Jahr 79 n. Chr. Pompeji?',
    options: ['Vesuv', 'Ätna', 'Stromboli', 'Vulcano'],
    correct: 0,
    fact: 'vulkan:pompeji',
  },
  {
    id: 'b0160',
    cat: 'geografie',
    diff: 'mittel',
    text: 'Wie heißt die Hauptstadt von Ägypten?',
    options: ['Alexandria', 'Luxor', 'Kairo', 'Assuan'],
    correct: 2,
    fact: 'hauptstadt:aegypten',
  },
  {
    id: 'b0161',
    cat: 'geografie',
    diff: 'mittel',
    text: 'Welches Meer liegt zwischen Italien und der Balkanhalbinsel?',
    options: ['Ägäis', 'Ionisches Meer', 'Tyrrhenisches Meer', 'Adria'],
    correct: 3,
    fact: 'meer:italien-balkan',
  },
  {
    id: 'b0162',
    cat: 'geografie',
    diff: 'mittel',
    text: 'Wie heißt der höchste Berg Afrikas?',
    options: ['Mount Kenya', 'Kilimandscharo', 'Ruwenzori', 'Toubkal'],
    correct: 1,
    fact: 'berg:hoechster-afrika',
  },
  {
    id: 'b0163',
    cat: 'geografie',
    diff: 'mittel',
    text: 'Wie heißt die Hauptstadt von Indien?',
    options: ['Mumbai', 'Kolkata', 'Neu-Delhi', 'Bengaluru'],
    correct: 2,
    fact: 'hauptstadt:indien',
  },
  {
    id: 'b0164',
    cat: 'geografie',
    diff: 'mittel',
    text: 'Welcher Kleinstaat liegt zwischen Frankreich und Spanien?',
    options: ['Andorra', 'Monaco', 'Liechtenstein', 'Luxemburg'],
    correct: 0,
    fact: 'land:pyrenaeen-zwergstaat',
  },
  {
    id: 'b0165',
    cat: 'geografie',
    diff: 'mittel',
    text: 'Welches Gewässer trennt England vom Festland Frankreichs?',
    options: ['Ärmelkanal', 'Nordsee', 'Irische See', 'Skagerrak'],
    correct: 0,
    fact: 'meer:england-frankreich',
  },

  // ---------------------------------------------------------------------------
  // GEOGRAFIE — schwer
  // ---------------------------------------------------------------------------
  {
    id: 'b0166',
    cat: 'geografie',
    diff: 'schwer',
    text: 'Wie heißt die Hauptstadt von Neuseeland?',
    options: ['Auckland', 'Christchurch', 'Wellington', 'Dunedin'],
    correct: 2,
    fact: 'hauptstadt:neuseeland',
  },
  {
    id: 'b0167',
    cat: 'geografie',
    diff: 'schwer',
    text: 'Wie heißt die Hauptstadt von Marokko?',
    options: ['Casablanca', 'Marrakesch', 'Fès', 'Rabat'],
    correct: 3,
    fact: 'hauptstadt:marokko',
  },
  {
    id: 'b0168',
    cat: 'geografie',
    diff: 'schwer',
    text: 'Wie heißt die Hauptstadt von Vietnam?',
    options: ['Ho-Chi-Minh-Stadt', 'Hanoi', 'Da Nang', 'Hue'],
    correct: 1,
    fact: 'hauptstadt:vietnam',
  },
  {
    id: 'b0169',
    cat: 'geografie',
    diff: 'schwer',
    text: 'Wie heißt die Hauptstadt von Nigeria?',
    options: ['Lagos', 'Kano', 'Abuja', 'Ibadan'],
    correct: 2,
    fact: 'hauptstadt:nigeria',
  },
  {
    id: 'b0170',
    cat: 'geografie',
    diff: 'schwer',
    text: 'Welcher Fluss fließt durch Prag?',
    options: ['Moldau', 'Donau', 'Oder', 'Weichsel'],
    correct: 0,
    fact: 'fluss:prag',
  },
  {
    id: 'b0171',
    cat: 'geografie',
    diff: 'schwer',
    text: 'Welches Gebirge teilt Russland in einen europäischen und asiatischen Teil?',
    options: ['Kaukasus', 'Karpaten', 'Altai', 'Ural'],
    correct: 3,
    fact: 'gebirge:russland-teilung',
  },
  {
    id: 'b0172',
    cat: 'geografie',
    diff: 'schwer',
    text: 'Welcher See der Erde ist der tiefste?',
    options: ['Kaspisches Meer', 'Baikalsee', 'Tanganjikasee', 'Titicacasee'],
    correct: 1,
    fact: 'see:tiefster-welt',
  },
  {
    id: 'b0173',
    cat: 'geografie',
    diff: 'schwer',
    text: 'In welchem Land liegt die antike Felsenstadt Petra?',
    options: ['Jordanien', 'Syrien', 'Libanon', 'Israel'],
    correct: 0,
    fact: 'stadt:petra-land',
  },
  {
    id: 'b0174',
    cat: 'geografie',
    diff: 'schwer',
    text: 'Welcher Staat hat die kleinste Fläche der Welt?',
    options: ['Monaco', 'Nauru', 'Vatikanstadt', 'San Marino'],
    correct: 2,
    fact: 'land:kleinstes-welt',
  },
  {
    id: 'b0175',
    cat: 'geografie',
    diff: 'schwer',
    text: 'Welche Wüste erstreckt sich quer über Nordafrika?',
    options: ['Kalahari', 'Sahara', 'Namib', 'Gobi'],
    correct: 1,
    fact: 'wueste:nordafrika',
  },
  {
    id: 'b0176',
    cat: 'geografie',
    diff: 'schwer',
    text: 'An welchem Fluss liegt die Stadt Bagdad?',
    options: ['Euphrat', 'Jordan', 'Indus', 'Tigris'],
    correct: 3,
    fact: 'fluss:bagdad',
  },
  {
    id: 'b0177',
    cat: 'geografie',
    diff: 'schwer',
    text: 'Welcher Staat teilt sich die Insel Hispaniola mit Haiti?',
    options: ['Kuba', 'Jamaika', 'Puerto Rico', 'Dominikanische Republik'],
    correct: 3,
    fact: 'insel:hispaniola-nachbar',
  },
  {
    id: 'b0178',
    cat: 'geografie',
    diff: 'schwer',
    text: 'Wie heißt die Hauptstadt von Chile?',
    options: ['Valparaíso', 'Santiago', 'Concepción', 'Antofagasta'],
    correct: 1,
    fact: 'hauptstadt:chile',
  },
  {
    id: 'b0179',
    cat: 'geografie',
    diff: 'schwer',
    text: 'Welches Land wird vollständig von Südafrika umschlossen?',
    options: ['Lesotho', 'Eswatini', 'Botswana', 'Simbabwe'],
    correct: 0,
    fact: 'land:enklave-suedafrika',
  },
  {
    id: 'b0180',
    cat: 'geografie',
    diff: 'schwer',
    text: 'Auf welchem Kontinent liegt die Atacama-Wüste?',
    options: ['Afrika', 'Asien', 'Südamerika', 'Australien'],
    correct: 2,
    fact: 'wueste:atacama-kontinent',
  },
  // ---------------------------------------------------------------------------
  // TIERE — leicht
  // ---------------------------------------------------------------------------
  {
    id: 'b0181',
    cat: 'tiere',
    diff: 'leicht',
    text: 'Welches ist das schnellste Landtier der Welt?',
    answer: 'Gepard',
    fact: 'tier:schnellstes-landtier',
  },
  {
    id: 'b0182',
    cat: 'tiere',
    diff: 'leicht',
    text: 'Welches ist das größte Tier der Erde?',
    answer: 'Blauwal',
    fact: 'tier:groesstes-tier',
  },
  {
    id: 'b0183',
    cat: 'tiere',
    diff: 'leicht',
    text: 'Wie heißt das Jungtier eines Hundes?',
    answer: 'Welpe',
    accept: ['Welpen'],
    fact: 'tier:hund-jungtier',
  },
  {
    id: 'b0184',
    cat: 'tiere',
    diff: 'leicht',
    text: 'Wie heißt das Jungtier eines Schafes?',
    answer: 'Lamm',
    accept: ['Lämmchen'],
    fact: 'tier:schaf-jungtier',
  },
  {
    id: 'b0185',
    cat: 'tiere',
    diff: 'leicht',
    text: 'Welcher Vogel legt die größten Eier?',
    answer: 'Strauß',
    accept: ['Vogel Strauß'],
    fact: 'tier:groesstes-ei',
  },
  {
    id: 'b0186',
    cat: 'tiere',
    diff: 'leicht',
    text: 'Wie nennt man ein weibliches Pferd?',
    answer: 'Stute',
    fact: 'tier:weibliches-pferd',
  },
  {
    id: 'b0187',
    cat: 'tiere',
    diff: 'leicht',
    text: 'Welches Säugetier kann aktiv fliegen?',
    answer: 'Fledermaus',
    accept: ['Fledermäuse'],
    fact: 'tier:fliegendes-saeugetier',
  },
  {
    id: 'b0188',
    cat: 'tiere',
    diff: 'leicht',
    text: 'Welches ist das größte Landtier der Erde?',
    answer: 'Afrikanischer Elefant',
    accept: ['Elefant'],
    fact: 'tier:groesstes-landtier',
  },
  {
    id: 'b0189',
    cat: 'tiere',
    diff: 'leicht',
    text: 'Welches australische Beuteltier hüpft und boxt?',
    answer: 'Känguru',
    accept: ['Känguruh'],
    fact: 'tier:kaenguru',
  },
  {
    id: 'b0190',
    cat: 'tiere',
    diff: 'leicht',
    text: 'Wie viele Herzen hat ein Oktopus?',
    answer: 'drei',
    accept: ['3'],
    fact: 'tier:oktopus-herzen',
  },
  {
    id: 'b0191',
    cat: 'tiere',
    diff: 'leicht',
    text: 'Welches Tier hat den längsten Hals?',
    answer: 'Giraffe',
    fact: 'tier:laengster-hals',
  },
  {
    id: 'b0192',
    cat: 'tiere',
    diff: 'leicht',
    text: 'Welches Nagetier baut Dämme aus Holz?',
    answer: 'Biber',
    fact: 'tier:daemmebauer',
  },
  {
    id: 'b0193',
    cat: 'tiere',
    diff: 'leicht',
    text: 'Welches Tier wird auch „Wüstenschiff“ genannt?',
    answer: 'Kamel',
    accept: ['Dromedar'],
    fact: 'tier:wuestenschiff',
  },
  {
    id: 'b0194',
    cat: 'tiere',
    diff: 'leicht',
    text: 'Wie viele Höcker hat ein Dromedar?',
    answer: 'einen',
    accept: ['1', 'eins', 'ein'],
    fact: 'tier:dromedar-hoecker',
  },
  {
    id: 'b0195',
    cat: 'tiere',
    diff: 'leicht',
    text: 'Welcher Vogel lebt in der Antarktis und kann nicht fliegen?',
    answer: 'Pinguin',
    fact: 'tier:antarktis-vogel',
  },
  {
    id: 'b0196',
    cat: 'tiere',
    diff: 'leicht',
    text: 'Wie nennt man ein männliches Rind?',
    answer: 'Stier',
    accept: ['Bulle'],
    fact: 'tier:maennliches-rind',
  },
  {
    id: 'b0197',
    cat: 'tiere',
    diff: 'leicht',
    text: 'Welches Insekt produziert Honig?',
    answer: 'Biene',
    accept: ['Honigbiene'],
    fact: 'tier:honig',
  },
  {
    id: 'b0198',
    cat: 'tiere',
    diff: 'leicht',
    text: 'Welches Tier hat schwarz-weiße Streifen im Fell?',
    answer: 'Zebra',
    fact: 'tier:streifen',
  },
  {
    id: 'b0199',
    cat: 'tiere',
    diff: 'leicht',
    text: 'Welcher Fisch ist der größte der Welt?',
    answer: 'Walhai',
    fact: 'tier:groesster-fisch',
  },
  {
    id: 'b0200',
    cat: 'tiere',
    diff: 'leicht',
    text: 'Welcher Bär lebt in der Arktis?',
    answer: 'Eisbär',
    accept: ['Polarbär'],
    fact: 'tier:arktis-baer',
  },
  {
    id: 'b0201',
    cat: 'tiere',
    diff: 'leicht',
    text: 'Welches Tier frisst fast ausschließlich Eukalyptus?',
    answer: 'Koala',
    fact: 'tier:eukalyptus',
  },
  {
    id: 'b0202',
    cat: 'tiere',
    diff: 'leicht',
    text: 'Wie viele Beine hat ein Insekt?',
    answer: 'sechs',
    accept: ['6'],
    fact: 'tier:insekt-beine',
  },
  {
    id: 'b0203',
    cat: 'tiere',
    diff: 'leicht',
    text: 'Welches Säugetier legt Eier und lebt in Australien?',
    answer: 'Schnabeltier',
    accept: ['Ameisenigel'],
    fact: 'tier:eierlegendes-saeugetier',
  },
  {
    id: 'b0204',
    cat: 'tiere',
    diff: 'leicht',
    text: 'Wie nennt man ein weibliches Huhn?',
    answer: 'Henne',
    fact: 'tier:weibliches-huhn',
  },
  // ---------------------------------------------------------------------------
  // TIERE — mittel
  // ---------------------------------------------------------------------------
  {
    id: 'b0205',
    cat: 'tiere',
    diff: 'mittel',
    text: 'Wie heißt die Wissenschaft von den Vögeln?',
    answer: 'Ornithologie',
    fact: 'tier:ornithologie',
  },
  {
    id: 'b0206',
    cat: 'tiere',
    diff: 'mittel',
    text: 'Wie nennt man eine Gruppe von Löwen?',
    answer: 'Rudel',
    fact: 'tier:loewengruppe',
  },
  {
    id: 'b0207',
    cat: 'tiere',
    diff: 'mittel',
    text: 'Wie viele Mägen hat eine Kuh?',
    answer: 'vier',
    accept: ['4'],
    fact: 'tier:kuh-maegen',
  },
  {
    id: 'b0208',
    cat: 'tiere',
    diff: 'mittel',
    text: 'Welches Tier kann seine Augen unabhängig voneinander bewegen?',
    answer: 'Chamäleon',
    fact: 'tier:chamaeleon',
  },
  {
    id: 'b0209',
    cat: 'tiere',
    diff: 'mittel',
    text: 'Welches ist das größte Reptil der Welt?',
    answer: 'Salzwasserkrokodil',
    accept: ['Leistenkrokodil'],
    fact: 'tier:groesstes-reptil',
  },
  {
    id: 'b0210',
    cat: 'tiere',
    diff: 'mittel',
    text: 'Welches Landtier hat die längste Tragzeit?',
    answer: 'Elefant',
    accept: ['Afrikanischer Elefant'],
    fact: 'tier:tragzeit',
  },
  {
    id: 'b0211',
    cat: 'tiere',
    diff: 'mittel',
    text: 'Zu welcher Tierklasse gehören Frösche und Kröten?',
    answer: 'Amphibien',
    accept: ['Lurche'],
    fact: 'tier:amphibien',
  },
  {
    id: 'b0212',
    cat: 'tiere',
    diff: 'mittel',
    text: 'Wie nennt man Tiere, die sich nur von Pflanzen ernähren?',
    answer: 'Pflanzenfresser',
    accept: ['Herbivoren', 'Herbivore'],
    fact: 'tier:pflanzenfresser',
  },
  {
    id: 'b0213',
    cat: 'tiere',
    diff: 'mittel',
    text: 'Welches Tier ist der nächste lebende Verwandte der Giraffe?',
    answer: 'Okapi',
    fact: 'tier:okapi',
  },
  {
    id: 'b0214',
    cat: 'tiere',
    diff: 'mittel',
    text: 'Wie viele Arme hat ein Seestern typischerweise?',
    answer: 'fünf',
    accept: ['5'],
    fact: 'tier:seestern-arme',
  },
  {
    id: 'b0215',
    cat: 'tiere',
    diff: 'mittel',
    text: 'Welcher Vogel kann als einziger rückwärts fliegen?',
    answer: 'Kolibri',
    fact: 'tier:rueckwaerts-fliegen',
  },
  {
    id: 'b0216',
    cat: 'tiere',
    diff: 'mittel',
    text: 'Welche Affenart ist der nächste lebende Verwandte des Menschen?',
    answer: 'Schimpanse',
    accept: ['Bonobo'],
    fact: 'tier:naechster-verwandter',
  },
  {
    id: 'b0217',
    cat: 'tiere',
    diff: 'mittel',
    text: 'Welches Tier trägt den wissenschaftlichen Namen Panthera leo?',
    answer: 'Löwe',
    fact: 'tier:panthera-leo',
  },
  {
    id: 'b0218',
    cat: 'tiere',
    diff: 'mittel',
    text: 'Welches Tier trägt den wissenschaftlichen Namen Canis lupus?',
    answer: 'Wolf',
    fact: 'tier:canis-lupus',
  },
  {
    id: 'b0219',
    cat: 'tiere',
    diff: 'mittel',
    text: 'Welche ist die größte Katzenart der Welt?',
    answer: 'Tiger',
    fact: 'tier:groesste-katze',
  },
  {
    id: 'b0220',
    cat: 'tiere',
    diff: 'mittel',
    text: 'Welches Meeressäugetier orientiert sich mit Echoortung?',
    answer: 'Delfin',
    accept: ['Delphin'],
    fact: 'tier:echoortung',
  },
  {
    id: 'b0221',
    cat: 'tiere',
    diff: 'mittel',
    text: 'Wie viele Zähne hat ein erwachsener Hund?',
    answer: '42',
    accept: ['zweiundvierzig'],
    fact: 'tier:hund-zaehne',
  },
  {
    id: 'b0222',
    cat: 'tiere',
    diff: 'mittel',
    text: 'Welcher Vogel ist im Sturzflug der schnellste?',
    answer: 'Wanderfalke',
    fact: 'tier:sturzflug',
  },
  {
    id: 'b0223',
    cat: 'tiere',
    diff: 'mittel',
    text: 'Wie nennt man die Winterruhe von Fröschen und Reptilien?',
    answer: 'Winterstarre',
    fact: 'tier:winterstarre',
  },
  {
    id: 'b0224',
    cat: 'tiere',
    diff: 'mittel',
    text: 'Welches Tier ist das Wappentier des WWF?',
    answer: 'Großer Panda',
    accept: ['Panda', 'Pandabär'],
    fact: 'tier:wwf',
  },
  {
    id: 'b0225',
    cat: 'tiere',
    diff: 'mittel',
    text: 'Welcher Vogel legt seine Eier in fremde Nester?',
    answer: 'Kuckuck',
    fact: 'tier:brutparasit',
  },
  // ---------------------------------------------------------------------------
  // TIERE — schwer
  // ---------------------------------------------------------------------------
  {
    id: 'b0226',
    cat: 'tiere',
    diff: 'schwer',
    text: 'Wie lautet der wissenschaftliche Name des modernen Menschen?',
    answer: 'Homo sapiens',
    fact: 'tier:homo-sapiens',
  },
  {
    id: 'b0227',
    cat: 'tiere',
    diff: 'schwer',
    text: 'Welches Tier besitzt das größte Gehirn aller Lebewesen?',
    answer: 'Pottwal',
    fact: 'tier:groesstes-gehirn',
  },
  {
    id: 'b0228',
    cat: 'tiere',
    diff: 'schwer',
    text: 'Wie heißt die Ordnung, zu der die Fledermäuse gehören?',
    answer: 'Fledertiere',
    accept: ['Chiroptera'],
    fact: 'tier:chiroptera',
  },
  {
    id: 'b0229',
    cat: 'tiere',
    diff: 'schwer',
    text: 'Welches Insekt lebt als erwachsenes Tier oft nur einen Tag?',
    answer: 'Eintagsfliege',
    fact: 'tier:eintagsfliege',
  },
  {
    id: 'b0230',
    cat: 'tiere',
    diff: 'schwer',
    text: 'Wie heißt das einzige in Nordamerika heimische Beuteltier?',
    answer: 'Opossum',
    accept: ['Virginia-Opossum'],
    fact: 'tier:opossum',
  },
  {
    id: 'b0231',
    cat: 'tiere',
    diff: 'schwer',
    text: 'Wie viele Kammern hat das Herz eines Vogels?',
    answer: 'vier',
    accept: ['4'],
    fact: 'tier:vogelherz',
  },
  {
    id: 'b0232',
    cat: 'tiere',
    diff: 'schwer',
    text: 'Wie heißt der Tierstamm mit Außenskelett aus Chitin?',
    answer: 'Gliederfüßer',
    accept: ['Arthropoden'],
    fact: 'tier:gliederfuesser',
  },
  {
    id: 'b0233',
    cat: 'tiere',
    diff: 'schwer',
    text: 'Welcher Greifvogel hat die größte Spannweite an Land?',
    answer: 'Andenkondor',
    fact: 'tier:andenkondor',
  },
  {
    id: 'b0234',
    cat: 'tiere',
    diff: 'schwer',
    text: 'Wie heißt die Wissenschaft von den Insekten?',
    answer: 'Entomologie',
    fact: 'tier:entomologie',
  },
  {
    id: 'b0235',
    cat: 'tiere',
    diff: 'schwer',
    text: 'Welcher Vogel legt im Verhältnis zum Körper das größte Ei?',
    answer: 'Kiwi',
    fact: 'tier:kiwi-ei',
  },
  {
    id: 'b0236',
    cat: 'tiere',
    diff: 'schwer',
    text: 'Wie heißt die Umwandlung von der Raupe zum Schmetterling?',
    answer: 'Metamorphose',
    fact: 'tier:metamorphose',
  },
  {
    id: 'b0237',
    cat: 'tiere',
    diff: 'schwer',
    text: 'Wie viele Halswirbel hat eine Giraffe?',
    answer: 'sieben',
    accept: ['7'],
    fact: 'tier:giraffe-halswirbel',
  },
  {
    id: 'b0238',
    cat: 'tiere',
    diff: 'schwer',
    text: 'Zu welcher Klasse gehören Haie und Rochen?',
    answer: 'Knorpelfische',
    fact: 'tier:knorpelfische',
  },
  {
    id: 'b0239',
    cat: 'tiere',
    diff: 'schwer',
    text: 'Wie heißt die größte Robbenart der Welt?',
    answer: 'See-Elefant',
    accept: ['Seeelefant', 'Seeelefanten'],
    fact: 'tier:see-elefant',
  },
  {
    id: 'b0240',
    cat: 'tiere',
    diff: 'schwer',
    text: 'Welches Tier trägt den wissenschaftlichen Namen Vulpes vulpes?',
    answer: 'Rotfuchs',
    accept: ['Fuchs'],
    fact: 'tier:vulpes',
  },
  // ---------------------------------------------------------------------------
  // ANIME — leicht
  // ---------------------------------------------------------------------------
  {
    id: 'b0241',
    cat: 'anime',
    diff: 'leicht',
    text: 'Wie heißt der Ninja, in dem der Neunschwänzige Fuchs versiegelt ist?',
    answer: 'Naruto',
    accept: ['Naruto Uzumaki'],
    fact: 'anime:naruto-held',
  },
  {
    id: 'b0242',
    cat: 'anime',
    diff: 'leicht',
    text: 'In welchem Anime suchen Piraten den Schatz „One Piece“?',
    answer: 'One Piece',
    fact: 'anime:one-piece',
  },
  {
    id: 'b0243',
    cat: 'anime',
    diff: 'leicht',
    text: 'Wie heißt der Held von „Dragon Ball“?',
    answer: 'Son Goku',
    accept: ['Goku', 'Songoku'],
    fact: 'anime:goku',
  },
  {
    id: 'b0244',
    cat: 'anime',
    diff: 'leicht',
    text: 'Wie heißt Nezukos großer Bruder in „Demon Slayer“?',
    answer: 'Tanjiro',
    accept: ['Tanjiro Kamado'],
    fact: 'anime:tanjiro',
  },
  {
    id: 'b0245',
    cat: 'anime',
    diff: 'leicht',
    text: 'In welchem Anime kämpfen Menschen hinter Mauern gegen Titanen?',
    answer: 'Attack on Titan',
    accept: ['Shingeki no Kyojin'],
    fact: 'anime:aot',
  },
  {
    id: 'b0246',
    cat: 'anime',
    diff: 'leicht',
    text: 'Wie heißt das gelbe Elektro-Pokémon von Ash?',
    answer: 'Pikachu',
    fact: 'anime:pikachu',
  },
  {
    id: 'b0247',
    cat: 'anime',
    diff: 'leicht',
    text: 'Welches Studio produzierte „Chihiros Reise ins Zauberland“?',
    answer: 'Studio Ghibli',
    accept: ['Ghibli'],
    fact: 'anime:ghibli',
  },
  {
    id: 'b0248',
    cat: 'anime',
    diff: 'leicht',
    text: 'Wie heißt der Anime über ein Notizbuch, das tötet?',
    answer: 'Death Note',
    fact: 'anime:death-note',
  },
  {
    id: 'b0249',
    cat: 'anime',
    diff: 'leicht',
    text: 'Wie heißt Ashs Heimatstadt im deutschen „Pokémon“-Anime?',
    answer: 'Alabastia',
    accept: ['Pallet Town'],
    fact: 'anime:alabastia',
  },
  {
    id: 'b0250',
    cat: 'anime',
    diff: 'leicht',
    text: 'An welcher Heldenschule spielt „My Hero Academia“?',
    answer: 'U.A.',
    accept: ['UA', 'U.A. High', 'Yuei'],
    fact: 'anime:ua',
  },
  {
    id: 'b0251',
    cat: 'anime',
    diff: 'leicht',
    text: 'Wie heißt der blaue Roboter-Kater aus der Zukunft?',
    answer: 'Doraemon',
    fact: 'anime:doraemon',
  },
  {
    id: 'b0252',
    cat: 'anime',
    diff: 'leicht',
    text: 'Wie heißt der geschrumpfte Detektiv in „Detektiv Conan“?',
    answer: 'Conan Edogawa',
    accept: ['Conan', 'Shinichi Kudo'],
    fact: 'anime:conan',
  },
  {
    id: 'b0253',
    cat: 'anime',
    diff: 'leicht',
    text: 'Welcher Anime dreht sich um das Kartenspiel Duel Monsters?',
    answer: 'Yu-Gi-Oh',
    accept: ['Yu-Gi-Oh!', 'Yugioh'],
    fact: 'anime:yugioh',
  },
  {
    id: 'b0254',
    cat: 'anime',
    diff: 'leicht',
    text: 'Wie heißt der Shinigami, der Light das Notizbuch überlässt?',
    answer: 'Ryuk',
    fact: 'anime:ryuk',
  },
  {
    id: 'b0255',
    cat: 'anime',
    diff: 'leicht',
    text: 'Wie viele Dragon Balls braucht man, um Shenlong zu rufen?',
    answer: 'sieben',
    accept: ['7'],
    fact: 'anime:dragonballs',
  },
  {
    id: 'b0256',
    cat: 'anime',
    diff: 'leicht',
    text: 'Wie heißt der Kapitän der Strohhutbande in „One Piece“?',
    answer: 'Ruffy',
    accept: ['Monkey D. Ruffy', 'Luffy'],
    fact: 'anime:ruffy',
  },
  {
    id: 'b0257',
    cat: 'anime',
    diff: 'leicht',
    text: 'Wie heißt Narutos Rivale aus dem Uchiha-Klan?',
    answer: 'Sasuke',
    accept: ['Sasuke Uchiha'],
    fact: 'anime:sasuke',
  },
  {
    id: 'b0258',
    cat: 'anime',
    diff: 'leicht',
    text: 'In welchem Anime sucht ein Alchemist mit Metallarm den Stein der Weisen?',
    answer: 'Fullmetal Alchemist',
    fact: 'anime:fma',
  },
  {
    id: 'b0259',
    cat: 'anime',
    diff: 'leicht',
    text: 'Wie heißt die schwarze Katze in „Sailor Moon“?',
    answer: 'Luna',
    fact: 'anime:luna',
  },
  {
    id: 'b0260',
    cat: 'anime',
    diff: 'leicht',
    text: 'Welche Haarfarbe bekommt Son Goku als Super-Saiyajin?',
    answer: 'blond',
    accept: ['gelb', 'goldblond'],
    fact: 'anime:supersaiyajin',
  },
  {
    id: 'b0261',
    cat: 'anime',
    diff: 'leicht',
    text: 'Welcher Anime handelt von einer Volleyball-Mannschaft an der Oberschule?',
    answer: 'Haikyu',
    accept: ['Haikyuu', 'Haikyu!!'],
    fact: 'anime:haikyu',
  },
  {
    id: 'b0262',
    cat: 'anime',
    diff: 'leicht',
    text: 'Wie heißt der Hauptcharakter von „Death Note“?',
    answer: 'Light Yagami',
    accept: ['Light'],
    fact: 'anime:light',
  },
  {
    id: 'b0263',
    cat: 'anime',
    diff: 'leicht',
    text: 'In welchem Anime kämpfen Yuji Itadori und Sukuna?',
    answer: 'Jujutsu Kaisen',
    fact: 'anime:jjk',
  },
  {
    id: 'b0264',
    cat: 'anime',
    diff: 'leicht',
    text: 'Wie heißt Sasukes älterer Bruder in „Naruto“?',
    answer: 'Itachi',
    accept: ['Itachi Uchiha'],
    fact: 'anime:itachi',
  },
  // ---------------------------------------------------------------------------
  // ANIME — mittel
  // ---------------------------------------------------------------------------
  {
    id: 'b0265',
    cat: 'anime',
    diff: 'mittel',
    text: 'Wer zeichnet den Manga „One Piece“?',
    answer: 'Eiichiro Oda',
    accept: ['Oda'],
    fact: 'anime:oda',
  },
  {
    id: 'b0266',
    cat: 'anime',
    diff: 'mittel',
    text: 'Wer schuf den Manga „Naruto“?',
    answer: 'Masashi Kishimoto',
    accept: ['Kishimoto'],
    fact: 'anime:kishimoto',
  },
  {
    id: 'b0267',
    cat: 'anime',
    diff: 'mittel',
    text: 'Wer schuf „Dragon Ball“?',
    answer: 'Akira Toriyama',
    accept: ['Toriyama'],
    fact: 'anime:toriyama',
  },
  {
    id: 'b0268',
    cat: 'anime',
    diff: 'mittel',
    text: 'Welcher Regisseur gründete Studio Ghibli mit?',
    answer: 'Hayao Miyazaki',
    accept: ['Miyazaki'],
    fact: 'anime:miyazaki',
  },
  {
    id: 'b0269',
    cat: 'anime',
    diff: 'mittel',
    text: 'Mit welcher Technik erschafft Naruto Kopien von sich?',
    answer: 'Schattendoppelgänger',
    accept: ['Kage Bunshin', 'Schattendoppelgänger-Technik'],
    fact: 'anime:kagebunshin',
  },
  {
    id: 'b0270',
    cat: 'anime',
    diff: 'mittel',
    text: 'In welchem Jahr lief die erste Folge des „Pokémon“-Anime?',
    answer: '1997',
    fact: 'anime:pokemon-1997',
  },
  {
    id: 'b0271',
    cat: 'anime',
    diff: 'mittel',
    text: 'In welchem Anime wird Ichigo zum Ersatz-Todesgott?',
    answer: 'Bleach',
    fact: 'anime:bleach',
  },
  {
    id: 'b0272',
    cat: 'anime',
    diff: 'mittel',
    text: 'Wie lautet Ichigos Nachname in „Bleach“?',
    answer: 'Kurosaki',
    fact: 'anime:kurosaki',
  },
  {
    id: 'b0273',
    cat: 'anime',
    diff: 'mittel',
    text: 'Welches Studio animierte die ersten drei Staffeln von „Attack on Titan“?',
    answer: 'Wit Studio',
    accept: ['WIT'],
    fact: 'anime:wit',
  },
  {
    id: 'b0274',
    cat: 'anime',
    diff: 'mittel',
    text: 'Wie heißt Edward Elrics jüngerer Bruder?',
    answer: 'Alphonse',
    accept: ['Alphonse Elric', 'Al'],
    fact: 'anime:alphonse',
  },
  {
    id: 'b0275',
    cat: 'anime',
    diff: 'mittel',
    text: 'Wer verwandelt sich in „Demon Slayer“ in einen Dämon, bleibt aber gut?',
    answer: 'Nezuko',
    accept: ['Nezuko Kamado'],
    fact: 'anime:nezuko',
  },
  {
    id: 'b0276',
    cat: 'anime',
    diff: 'mittel',
    text: 'Wie lautet Erens Nachname in der deutschen Fassung von „Attack on Titan“?',
    answer: 'Jäger',
    accept: ['Yeager', 'Jaeger'],
    fact: 'anime:jaeger',
  },
  {
    id: 'b0277',
    cat: 'anime',
    diff: 'mittel',
    text: 'Wie heißt der Hauptcharakter von „My Hero Academia“?',
    answer: 'Izuku Midoriya',
    accept: ['Deku', 'Midoriya'],
    fact: 'anime:midoriya',
  },
  {
    id: 'b0278',
    cat: 'anime',
    diff: 'mittel',
    text: 'Wie heißt die Kraft, die All Might an Izuku weitergibt?',
    answer: 'One For All',
    fact: 'anime:oneforall',
  },
  {
    id: 'b0279',
    cat: 'anime',
    diff: 'mittel',
    text: 'In welchem Anime kämpfen Jäger mit der Energie „Nen“?',
    answer: 'Hunter x Hunter',
    accept: ['Hunter × Hunter', 'HxH'],
    fact: 'anime:hxh',
  },
  {
    id: 'b0280',
    cat: 'anime',
    diff: 'mittel',
    text: 'Welcher Anime handelt von einem Helden, der alles mit einem Schlag besiegt?',
    answer: 'One Punch Man',
    fact: 'anime:opm',
  },
  {
    id: 'b0281',
    cat: 'anime',
    diff: 'mittel',
    text: 'Wie heißt der Held von „One Punch Man“?',
    answer: 'Saitama',
    fact: 'anime:saitama',
  },
  {
    id: 'b0282',
    cat: 'anime',
    diff: 'mittel',
    text: 'In welchem Anime jagen Schwertkämpfer Dämonen mit Atemtechniken?',
    answer: 'Demon Slayer',
    accept: ['Kimetsu no Yaiba'],
    fact: 'anime:demonslayer',
  },
  {
    id: 'b0283',
    cat: 'anime',
    diff: 'mittel',
    text: 'Wie heißt der Mecha-Anime von 1995 mit dem Piloten Shinji?',
    answer: 'Neon Genesis Evangelion',
    accept: ['Evangelion'],
    fact: 'anime:evangelion',
  },
  {
    id: 'b0284',
    cat: 'anime',
    diff: 'mittel',
    text: 'Wie heißt Makoto Shinkais Film über zwei Jugendliche, die die Körper tauschen?',
    answer: 'Your Name',
    accept: ['Kimi no Na wa'],
    fact: 'anime:yourname',
  },
  {
    id: 'b0285',
    cat: 'anime',
    diff: 'mittel',
    text: 'Wie heißt die Ninja-Organisation mit den roten Wolken in „Naruto“?',
    answer: 'Akatsuki',
    fact: 'anime:akatsuki',
  },
  // ---------------------------------------------------------------------------
  // ANIME — schwer
  // ---------------------------------------------------------------------------
  {
    id: 'b0286',
    cat: 'anime',
    diff: 'schwer',
    text: 'Welcher Verlag gibt das Magazin „Shonen Jump“ heraus?',
    answer: 'Shueisha',
    fact: 'anime:shueisha',
  },
  {
    id: 'b0287',
    cat: 'anime',
    diff: 'schwer',
    text: 'Wer führte Regie bei „Neon Genesis Evangelion“?',
    answer: 'Hideaki Anno',
    accept: ['Anno'],
    fact: 'anime:anno',
  },
  {
    id: 'b0288',
    cat: 'anime',
    diff: 'schwer',
    text: 'Welches Studio animiert „Demon Slayer“?',
    answer: 'Ufotable',
    fact: 'anime:ufotable',
  },
  {
    id: 'b0289',
    cat: 'anime',
    diff: 'schwer',
    text: 'Wer schuf den Manga „Attack on Titan“?',
    answer: 'Hajime Isayama',
    accept: ['Isayama'],
    fact: 'anime:isayama',
  },
  {
    id: 'b0290',
    cat: 'anime',
    diff: 'schwer',
    text: 'Wer schrieb den Manga „Death Note“?',
    answer: 'Tsugumi Ohba',
    accept: ['Ohba'],
    fact: 'anime:ohba',
  },
  {
    id: 'b0291',
    cat: 'anime',
    diff: 'schwer',
    text: 'Wer schuf den Manga „Sailor Moon“?',
    answer: 'Naoko Takeuchi',
    accept: ['Takeuchi'],
    fact: 'anime:takeuchi',
  },
  {
    id: 'b0292',
    cat: 'anime',
    diff: 'schwer',
    text: 'In welchem Jahr kam der Anime-Film „Akira“ in die Kinos?',
    answer: '1988',
    fact: 'anime:akira-jahr',
  },
  {
    id: 'b0293',
    cat: 'anime',
    diff: 'schwer',
    text: 'Wer führte Regie bei „Akira“?',
    answer: 'Katsuhiro Otomo',
    accept: ['Otomo'],
    fact: 'anime:otomo',
  },
  {
    id: 'b0294',
    cat: 'anime',
    diff: 'schwer',
    text: 'Wie heißt Miyazakis Film von 1997 über Waldgeister und eine Eisenhütte?',
    answer: 'Prinzessin Mononoke',
    accept: ['Mononoke'],
    fact: 'anime:mononoke',
  },
  {
    id: 'b0295',
    cat: 'anime',
    diff: 'schwer',
    text: 'Welches Studio produzierte „Cowboy Bebop“?',
    answer: 'Sunrise',
    fact: 'anime:sunrise',
  },
  {
    id: 'b0296',
    cat: 'anime',
    diff: 'schwer',
    text: 'Wie heißt der Kopfgeldjäger im Mittelpunkt von „Cowboy Bebop“?',
    answer: 'Spike Spiegel',
    accept: ['Spike'],
    fact: 'anime:spike',
  },
  {
    id: 'b0297',
    cat: 'anime',
    diff: 'schwer',
    text: 'Wer schuf den Manga „Fullmetal Alchemist“?',
    answer: 'Hiromu Arakawa',
    accept: ['Arakawa'],
    fact: 'anime:arakawa',
  },
  {
    id: 'b0298',
    cat: 'anime',
    diff: 'schwer',
    text: 'Wer schuf den Manga „Jujutsu Kaisen“?',
    answer: 'Gege Akutami',
    accept: ['Akutami'],
    fact: 'anime:akutami',
  },
  {
    id: 'b0299',
    cat: 'anime',
    diff: 'schwer',
    text: 'Wer schuf den Manga „Hunter x Hunter“?',
    answer: 'Yoshihiro Togashi',
    accept: ['Togashi'],
    fact: 'anime:togashi',
  },
  {
    id: 'b0300',
    cat: 'anime',
    diff: 'schwer',
    text: 'Wie heißt Osamu Tezukas Anime-Serie von 1963?',
    answer: 'Astro Boy',
    accept: ['Tetsuwan Atom'],
    fact: 'anime:astroboy',
  },
];

export default BANK;
